ava-labs/core-mobile

- packages/core-mobile/e2e/config.json
- packages/core-mobile/e2e/sendResults.ts
- packages/core-mobile/scripts/bitrise/detox/androidInternalE2eReuseAppState.sh
- packages/core-mobile/scripts/bitrise/detox/androidInternalRegressionRunner.sh
- packages/core-mobile/scripts/bitrise/detox/distributeAndroidTests.sh
- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- Added more logging to the distribute android test script.  Could not find issue with it yet.
- Fixed the regression run test distribution and it will now run full regression rather than just the smoke tests
> Qa fix fail on retry

- packages/core-mobile/e2e/configs/reuseStateConfig.json
- packages/core-mobile/e2e/configs/smokeTestConfigReuseState.json
- packages/core-mobile/e2e/locators/send.loc.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- packages/core-mobile/e2e/pages/connectToSite.page.ts
- packages/core-mobile/e2e/pages/connectedSites.page.ts
- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/pages/send.page.ts
- packages/core-mobile/e2e/tests/inAppBrowser/coreWebWCIntegration.e2e.smoke.ts
- packages/core-mobile/e2e/tests/inAppBrowser/rpcCallsPlayground.e2e.ts
- packages/core-mobile/e2e/tests/network/addCustomToken.e2e.smoke.ts
- packages/core-mobile/e2e/tests/network/changeNetwork.e2e.smoke.ts
- packages/core-mobile/e2e/tests/network/emptyAssets.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/parameterizedSend.e2e.singleRunner.ts
- packages/core-mobile/e2e/tests/plusIcon/send/sendSepoliaEthTo2ndAccount.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrations.e2e.ts
This should fix some tests. 
- Fixed regression testing for both iOS and Android
- Tested on both platforms 
> QA - fix regression tests

- packages/core-mobile/e2e/pages/createPin.page.ts
- packages/core-mobile/e2e/tests/portfolioTab/favoritesToken.e2e.ts
- Fix changePin and favorites token tests
> QA - Fix changePin and favorite tokens test 

- .github/dependabot.yml
- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- yarn.lock
* updated
* https://github.com/ava-labs/core-mobile/pull/1519
* https://github.com/ava-labs/core-mobile/pull/1520
* https://github.com/ava-labs/core-mobile/pull/1521
* https://github.com/ava-labs/core-mobile/pull/1523
* ignored
* https://github.com/ava-labs/core-mobile/pull/1522
> CP-9109: Update dependencies - Phase 3

- packages/core-mobile/app/temp/caip2ChainIds.ts
* return correct chain id for testnet chain
> fix: return correct chain id for testnet c chain

- docs/dependencies_resolutions.md
- package.json
- packages/core-mobile/package.json
- packages/eslint-mobile/package.json
- yarn.lock
> CP-9109: Update dependencies - Phase 8

- .github/dependabot.yml
> Update dependencies - fix typo

- packages/core-mobile/app/services/network/NetworkService.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
**Ticket: [CP-9161]** 
https://github.com/user-attachments/assets/afe09e5a-a50e-4a40-a708-361d5e09857a
[CP-9161]: https://ava-labs.atlassian.net/browse/CP-9161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9161: Fix 'no provider found' error

- packages/core-mobile/app/screens/rpc/components/shared/SimplePrompt.tsx
- packages/core-mobile/app/screens/rpc/components/v2/ApprovalPopup.tsx
- packages/core-mobile/e2e/locators/swapTab.loc.ts
- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/pages/swapTab.page.ts
- packages/core-mobile/e2e/tests/nft/sendNftError.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/send/send.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/send/sendEth.e2e.ts
- packages/core-mobile/e2e/tests/stake/stakingTestnet.e2e.ts
- tested on both iOS and Android
> QA - fix regression test

- packages/core-mobile/app/screens/drawer/sendFeedback/SendFeedback.tsx
**Ticket: [CP-9193]** 
* Auto-select Mobile Platform (iOS/Android) in Feedback Form 
| iOS | Android |
| --- | --- |
| <img src=https://github.com/user-attachments/assets/f59d0769-cbf4-4d46-999b-8cee63d74694 width=320 /> | <img src=https://github.com/user-attachments/assets/734d094b-01b3-4ddc-8d3d-fcf520ffb5d9 width=320 /> |
* Please verify if the first question in the feedback form is pre-selected with the correct option based on the platform.
[CP-9193]: https://ava-labs.atlassian.net/browse/CP-9193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9193: Auto-select Mobile Platform (iOS/Android) in Feedback Form 

- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- yarn.lock
- very simple ticket to update our datadog dependency
> QA update datadog deps

- packages/core-mobile/app/components/Avatar.tsx
- packages/core-mobile/app/screens/browser/utils.ts
**Ticket: [CP-9263]** 
[CP-9263]: https://ava-labs.atlassian.net/browse/CP-9263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9263: add base64 image data support

- packages/core-mobile/e2e/helpers/loginRecoverWallet.ts
- packages/core-mobile/e2e/locators/commonEls.loc.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- The new notification modal is blocking the automation testing and it should handle the onboarding issue 
> QA - handle notification modal during the onboarding 

- packages/core-mobile/app/screens/bridge/components/BridgeTransactionItem.tsx
- packages/core-mobile/e2e/helpers/loginRecoverWallet.ts
- packages/core-mobile/e2e/pages/Stake/stake.page.ts
- packages/core-mobile/e2e/pages/swapTab.page.ts
- packages/core-mobile/e2e/tests/settings/enableTestnet.e2e.smoke.ts
- add `await` during the onboarding method calls. 
- fix small tests 
> QA - fix smoke tests 

- packages/core-mobile/app/screens/portfolio/home/Portfolio.tsx
**Ticket: [CP-9278]** 
[CP-9278]: https://ava-labs.atlassian.net/browse/CP-9278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9278: fixed useCallback not used properly

- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/pages/portfolio.page.ts
- packages/core-mobile/e2e/tests/activityTab/activityTab.e2e.smoke.ts
- packages/core-mobile/e2e/tests/plusIcon/send/sendEth.e2e.ts
> QA - Fix tests 

- packages/core-mobile/app/components/InputText.tsx
- packages/core-mobile/e2e/attachLogsSendResultsToTestrail.ts
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/helpers/web.ts
- packages/core-mobile/e2e/locators/browser.loc.ts
- packages/core-mobile/e2e/pages/browser.page.ts
- packages/core-mobile/e2e/pages/collectibles.page.ts
- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/tests/browser/suggestedBrowsers.e2e.ts
- packages/core-mobile/e2e/tests/nft/sendEthNft.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrationsCore.e2e.smoke.ts
- New test: Send NFT in Ethereum network 
- New test: 
- Browser tab's default suggested dapp list 
- Browser tab's default suggested dapp list's url 
- Fix sending test results to testrail 
> QA - new tests and fix sending result to testrail 

- .github/dependabot.yml
- packages/core-mobile/package.json
- packages/core-mobile/tests/msw/native/handlers.ts
- packages/core-mobile/tests/msw/node/handlers.ts
- yarn.lock
> Update msw to 2.4.9

- packages/core-mobile/app/components/NetworkFeeSelector.tsx
- packages/core-mobile/app/screens/rpc/components/shared/DetailSectionView.tsx
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/locators/popupModal.loc.ts
- packages/core-mobile/e2e/pages/collectibles.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/pages/send.page.ts
- packages/core-mobile/e2e/pages/swapTab.page.ts
- packages/core-mobile/e2e/tests/plusIcon/send/send.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/send/sendEth.e2e.ts
- We're now testing fee amounts on all networks on the approve transaction screen. We should test if it's not too much or 0 
- Coverage - Send/Swap/Send
> QA New: approve transaction screen fee testing

- packages/core-mobile/detox.config.js
- packages/core-mobile/e2e/attachLogsSendResultsToTestrail.ts
- packages/core-mobile/e2e/sendResults.ts
- packages/core-mobile/e2e/tsconfig.json
- packages/core-mobile/scripts/bitrise/detox/androidE2ENoReuseAppState.sh
> QA - add tsconfig for e2e to avoid import issues

- packages/core-mobile/e2e/configs/regressionConfig.json
- packages/core-mobile/e2e/locators/collectibles.loc.ts
- packages/core-mobile/e2e/pages/collectibles.page.ts
- packages/core-mobile/e2e/pages/createPin.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/nft/sendEthNft.e2e.ts
- packages/core-mobile/e2e/tests/nft/sendNftError.e2e.ts
- packages/core-mobile/e2e/tests/settings/coreAnalytics.e2e.smoke.ts
- Tested on both iOS Android 
- Handle flaky tests 
> QA - fix automation tests

- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- packages/core-mobile/scripts/datadog/updateIosDashboard.sh
- Adds a curl command to update the memory use monitor to latest external build
- Adds env variable $BUILD_NUMBER to update the monitor to latest version
> Qa add memory use monitor

- packages/core-mobile/app/hooks/earn/useGetClaimableBalance.ts
**Ticket: [CP-9357]** 
Minor change
Balance should be correctly displayed now
[CP-9357]: https://ava-labs.atlassian.net/browse/CP-9357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9357 Fix load Stake balance 

- packages/core-mobile/app/screens/rpc/components/v2/ApprovalPopup.tsx
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/locators/popupModal.loc.ts
- packages/core-mobile/e2e/pages/collectibles.page.ts
- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/network/changeNetwork.e2e.smoke.ts
- handle flaky tests 
- scrollToBottom() and scrollToTop() methods would be useful in the future. 
> QA - automation fixes

- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- packages/core-mobile/scripts/datadog/updateAndroidDashboard.sh
- packages/core-mobile/scripts/datadog/updateIosDashboard.sh
- Add frozen frames percent monitor for iOS and Android 
- Add frozen frames widget to ios and android dashboards
- Added new frozen frame widgets for android and ios dashboards
> Qa update android dashboard

- packages/core-mobile/app/utils/debugging/DevDebuggingConfig.ts
- packages/core-mobile/e2e/locators/portfolio.loc.ts
- packages/core-mobile/e2e/pages/portfolio.page.ts
- packages/core-mobile/e2e/pages/send.page.ts
- packages/core-mobile/e2e/tests/plusIcon/send/send.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrationsRPCPlayground.e2e.ts
- packages/core-mobile/index.js
- handle some flaky tests on ios and android. 
> QA handle flaky tests and add logbox_disabled in devConfig

- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- packages/core-mobile/scripts/datadog/updateIosDashboard.sh
- Updates click or tap monitor threshold to 150ms from 15ms.  15ms is way to short of a duration.
> Qa update click or tap threshold monitor

- packages/core-mobile/app/services/datadog/DataDogConfig.ts
- packages/core-mobile/scripts/datadog/updateAndroidDashboard.sh
- Adds the tracking consent for the CI env
- Fixes some of the android events that weren't being sent to datadog
> Qa add dd tracking consent

- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/pages/swapTab.page.ts
- packages/core-mobile/e2e/tests/plusIcon/swap/swap.e2e.parameterized.ts
- packages/core-mobile/e2e/tests/plusIcon/swap/swap.e2e.smoke.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrationsCore.e2e.smoke.ts
- sometimes swap fails because of amount is not enough. We'll update the swap amount every time we see amount-related errors. 
- Sometimes core.app connect test fails because core.app is not loading properly on the web side. We'll check the error first and then proceed the test
- these should handle flakyness  
- Tested on both iOS and Android
> QA - Handle swap failures and other test fixes 

- packages/core-mobile/app/contexts/SendContext.tsx
- packages/core-mobile/app/screens/nft/send/NftSend.tsx
- packages/core-mobile/app/screens/send/SendTokenScreen.tsx
- packages/core-mobile/app/screens/send/components/SendAVM.tsx
- packages/core-mobile/app/screens/send/components/SendBTC.tsx
- packages/core-mobile/app/screens/send/components/SendEVM.tsx
- packages/core-mobile/app/screens/send/components/SendPVM.tsx
- packages/core-mobile/app/screens/send/components/SendTokenForm.tsx
- packages/core-mobile/app/screens/send/hooks/useAVMSend.ts
- packages/core-mobile/app/screens/send/hooks/useBTCSend.ts
- packages/core-mobile/app/screens/send/hooks/useEVMSend.ts
- packages/core-mobile/app/screens/send/hooks/useNativeTokenWithBalance.ts
- packages/core-mobile/app/screens/send/hooks/usePVMSend.ts
- packages/core-mobile/app/screens/send/utils/avm/validate.ts
- packages/core-mobile/app/screens/send/utils/evm/validate.ts
- packages/core-mobile/app/screens/send/utils/pvm/validate.test.ts
- packages/core-mobile/app/screens/send/utils/pvm/validate.ts
* cache native token to avoid unnecessary rerenders
* fix ui bugs in send flows
https://github.com/user-attachments/assets/5affb1f9-ad30-4cf6-bbd4-170784f31d36
> Fix UI bugs in send flow

- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/helpers/web.ts
- packages/core-mobile/e2e/pages/browser.page.ts
- packages/core-mobile/e2e/tests/network/addCustomNetwork.e2e.smoke.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappSwap.e2e.ts
- New - Swap testing via Dapp LFJ & UniSwap. Aave/SushiSwap/PancakeSwap were unstable to be automated. LFJ and UniSwap should be working fine  
- Fix - Handle some unstableness around webView testing. 
- Tested on both iOS and Android
> QA New - Swap Testing via Dapp 

- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- packages/k2-alpine/babel.config.js
- packages/k2-alpine/package.json
- packages/k2-alpine/src/components/PinInput/PinInput.stories.tsx
- packages/k2-alpine/src/components/PinInput/PinInput.tsx
- yarn.lock
**Ticket: [CP-9320]** 
* implement PINInput and animations for the new design
* add a story to demonstrate PINInput
https://github.com/user-attachments/assets/8fe85b0b-131c-4bea-b402-832655aa6968
[CP-9320]: https://ava-labs.atlassian.net/browse/CP-9320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9320: PIN - keypad number type

- packages/core-mobile/app/screens/activity/hooks/useBlockchainNames.ts
- packages/core-mobile/app/screens/shared/ActivityList/ActivityList.tsx
- packages/core-mobile/app/screens/shared/ActivityList/Transactions.tsx
- packages/core-mobile/app/services/activity/ActivityService.tsx
- packages/core-mobile/app/services/activity/types.ts
- packages/core-mobile/app/services/activity/utils/convertTransaction.ts
- packages/core-mobile/app/store/balance/listeners.ts
- packages/core-mobile/app/store/transaction/types.ts
**Ticket: [CP-9550]** 
* fix race condition between UnifiedBridgeService.init and UnifiedBridgeService.analyzeTx
[CP-9550]: https://ava-labs.atlassian.net/browse/CP-9550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9550: fix Missing P and X Chain on Portfolio

- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/core-mobile/app/new/utils/clipboard.ts
**Ticket: [CP-9602]** 
* Implement `copyToClipboard` function to copy a string value to clipboard and show the new snackbar
https://github.com/user-attachments/assets/98726f76-1fa4-4e93-b4ef-7cdf88ddb6d4
[CP-9602]: https://ava-labs.atlassian.net/browse/CP-9602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9602: K2 Clipboard

- packages/core-mobile/app/components/Avatar.tsx
- packages/core-mobile/app/screens/watchlist/components/WatchListItem.tsx
**Ticket: [CP-9622]** 
* show borders for token logos in watchlist
[CP-9622]: https://ava-labs.atlassian.net/browse/CP-9622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9622: Show borders for token logos in watchlist

- packages/core-mobile/e2e/helpers/web.ts
- packages/core-mobile/e2e/pages/browser.page.ts
- packages/core-mobile/e2e/pages/tokenDetail.page.ts
- packages/core-mobile/e2e/tests/dapps/walletConnect/connectDapps.e2e.ts
- packages/core-mobile/e2e/tests/dapps/walletConnect/connectPlayground.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/send/send.e2e.ts
> QA - automation small fixes

- packages/core-mobile/app/services/bridge/UnifiedBridgeService.ts
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-9719]** 
Please test all bridging again
[CP-9719]: https://ava-labs.atlassian.net/browse/CP-9719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9719: Update unified bridge sdk to latest

- packages/core-mobile/app/services/bridge/UnifiedBridgeService.ts
> allow undefined fee for ICTT

- packages/core-mobile/e2e/locators/Stake/stakeScreen.loc.ts
- packages/core-mobile/e2e/locators/connectToSite.loc.ts
- packages/core-mobile/e2e/locators/send.loc.ts
- packages/core-mobile/e2e/pages/Stake/duration.page.ts
- packages/core-mobile/e2e/pages/Stake/stake.page.ts
- packages/core-mobile/e2e/pages/browser.page.ts
- packages/core-mobile/e2e/pages/connectToSite.page.ts
- packages/core-mobile/e2e/tests/stake/stakingTestnet.e2e.ts
- Fix some of the automation failures 
- Tested on both iOS and Android
> QA - fix automation

- packages/core-mobile/app/new/features/onboarding/components/CreatePin.tsx
- packages/core-mobile/app/new/features/onboarding/components/EnterRecoveryPhrase.tsx
- packages/core-mobile/app/new/features/onboarding/components/RecoveryPhraseInput.tsx
- packages/core-mobile/app/new/features/onboarding/hooks/useCreatePin.ts
- packages/core-mobile/app/new/routes/+not-found.tsx
- packages/core-mobile/app/new/routes/accessWallet.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/_layout.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/analyticsConsent.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/createPin.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/enterRecoveryPhrase.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/setWalletName.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/createPin.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/setWalletName.tsx
- packages/k2-alpine/package.json
- yarn.lock
**Ticket: [CP-9696]** 
* Implemented the functionality to log in to an existing wallet by importing a mnemonic.
https://github.com/user-attachments/assets/9a057ff2-161e-4288-9af9-9c88fa1aa5ce
[CP-9696]: https://ava-labs.atlassian.net/browse/CP-9696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9696: Enter Recovery Phrase

- packages/core-mobile/app/store/balance/utils.tests.ts
**Ticket: [CP-9670]** 
- add unit tests
[CP-9670]: https://ava-labs.atlassian.net/browse/CP-9670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9670: add unit tests for balance store utils

- packages/core-mobile/app/components/Tooltip/Tooltip.tsx
- fix tooltip text and icon alignment.
> fix tooltip

- packages/core-mobile/app/navigation/AppNavigation.ts
- packages/core-mobile/app/navigation/wallet/EarnScreenStack/EarnScreenStack.tsx
- packages/core-mobile/app/navigation/wallet/EarnScreenStack/StakeSetupScreenStack.tsx
- packages/core-mobile/app/screens/earn/ClaimRewards.tsx
- packages/core-mobile/app/screens/earn/FundsStuckModal.tsx
- packages/core-mobile/app/services/earn/utils.ts
> Adjust error message for claim funds stuck modal

- packages/core-mobile/app/errors/swapError.ts
update high price impact swap error message
> update swap error message for high price impact

- packages/core-mobile/app/errors/swapError.ts
> update swap error message

- packages/core-mobile/app/screens/browser/Browser.tsx
**Ticket: [CP-9750]** 
This is best effort to fix keyboard pushing fixed web components out of screen.
https://github.com/user-attachments/assets/8d005ba8-4478-4ca6-a78b-251637adfb08
Please check Jira ticket for steps to reproduce bug, hence it's absence.
[CP-9750]: https://ava-labs.atlassian.net/browse/CP-9750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9750 Fix In-app browser cutting off token search bar in LFJ

- packages/core-mobile/app/screens/browser/Browser.tsx
**Ticket: [CP-9750]** 
Revert CP-9750
[CP-9750]: https://ava-labs.atlassian.net/browse/CP-9750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert CP-9750

- packages/core-mobile/app/services/earn/computeDelegationSteps/utils.ts
- packages/core-mobile/app/utils/network/glacier.ts
- packages/core-mobile/app/utils/network/glacierApi.client.ts
**Ticket: [CP-9880]** 
For cases where we need to transfer some AVAX from C-Chain, we were assuming P-Chain balance would be smaller than the stake amount. However, it is possible that staking amount is smaller in some situations. For example, if stake amount is 25 and P-Chain balance is 25.000001, the P-Chain balance is bigger here but it is not enough to cover fee. With the previous code, our math would come out negative resulting in a computation error. The fix is just to make sure we get the absolute difference.
This pr also fixes https://ava-labs.atlassian.net/browse/CP-9881 by upgrading the generated glacier schemas
[CP-9880]: https://ava-labs.atlassian.net/browse/CP-9880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> CP-9880: Fix unable to stake

- packages/core-mobile/app/new/common/components/SimpleTextInput.tsx
- packages/core-mobile/app/new/features/onboarding/components/AddRecoveryMethods.tsx
- packages/core-mobile/app/new/features/onboarding/components/FidoNameInput.tsx
- packages/core-mobile/app/new/features/onboarding/components/RecoveryMethodList.tsx
- packages/core-mobile/app/new/features/onboarding/components/SetWalletName.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/(fido)/_layout.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/(totp)/_layout.tsx
- packages/k2-alpine/src/components/Toast/NotificationAlert.tsx
- packages/k2-alpine/src/components/Toast/Snackbar.tsx
**Ticket: [CP-9875]** 
* fix layout issues with selection in `RecoveryMethodList`
* use `SimpleTextInput` in `FidoNameInput`
* refactoring
[CP-9875]: https://ava-labs.atlassian.net/browse/CP-9875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9875: Design feedback - Onboarding

- packages/core-mobile/app/screens/nft/send/NftSend.tsx
- packages/core-mobile/e2e/helpers/tokens.ts
- packages/core-mobile/e2e/helpers/web.ts
- packages/core-mobile/e2e/locators/Stake/confirmStaking.loc.ts
- packages/core-mobile/e2e/pages/browser.page.ts
- packages/core-mobile/e2e/pages/connectToSite.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/dapps/walletConnect/connectDapps.e2e.ts
- packages/core-mobile/e2e/tests/dapps/walletConnect/swapDapps.e2e.ts
I've been stepping away from the automated tests for manual testings last 1-2 weeks. I am putting a fix for failing tests 
> QA - fix daily automated tests

- packages/core-mobile/app/new/features/portfolio/components/ActionButtons.tsx
- packages/core-mobile/app/new/features/portfolio/components/assets/TokenGridView.tsx
- packages/core-mobile/app/new/features/portfolio/components/assets/TokenListItem.tsx
- packages/core-mobile/app/new/features/portfolio/components/assets/TokenListView.tsx
- packages/core-mobile/app/new/features/portfolio/components/assets/types.ts
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/core-mobile/app/store/balance/slice.ts
- packages/k2-alpine/src/components/PriceChangeIndicator/PriceChangeIndicator.tsx
**Ticket: [CP-9915]** 
- fix action buttons list doesn't show correct background in dark mode
- filter out zero balance tokens
- do not show arrowUp icon when status is equal
[CP-9915]: https://ava-labs.atlassian.net/browse/CP-9915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9915: Fix portfolio bugs

- packages/core-mobile/app/screens/watchlist/useTokenSearch.ts
- packages/core-mobile/app/services/watchlist/WatchlistService.ts
**Ticket: [CP-9814]** 
Please check commens for explanation
[CP-9814]: https://ava-labs.atlassian.net/browse/CP-9814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9814: Fix price of tokens showing $0.00 when being searched on the watchlist

- packages/core-mobile/app/seedless/hooks/useVerifyMFA.ts
**Ticket: [CP-9955]** 
we were passing the wrong mfa ID to the request. this pr fixes that.
[CP-9955]: https://ava-labs.atlassian.net/browse/CP-9955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9955: Fix unable to add/remove MFA

- packages/core-mobile/app/store/rpc/handlers/wc_sessionRequest/utils.ts
> add core web redesign url regex

- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
- packages/core-mobile/app/store/balance/types.ts
- add x/p chain to portfolio filter list
https://github.com/user-attachments/assets/b213b693-f51f-4fb2-95d2-a4c3aa749a84
> Add x/p filter to portoflio

- packages/core-mobile/app/screens/rpc/components/v2/ApprovalPopup.tsx
- packages/core-mobile/app/services/gasless/GaslessService.ts
**Ticket: [CP-9983]** 
This adds logic to wait for confirmation of funding before proceeding to send or other actions.
[CP-9983]: https://ava-labs.atlassian.net/browse/CP-9983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9983: Add waitForConfirmation of fundTx

- packages/core-mobile/app/new/common/hooks/useFadingHeaderNavigation.tsx
- packages/core-mobile/app/new/features/onboarding/components/CreatePin.tsx
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
* focus text input after finishing interaction
* fix showing grabber when header has title fade effect
> Focus textinput after finishing interaction

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
- packages/core-mobile/app/screens/watchlist/useTokenDetails.ts
- packages/core-mobile/app/services/token/types.ts
**Ticket: [CP-9705]** 
- set token only once since the data doesn't change
- hide `SelectedChartDataIndicator` if user is not interacting with chart
- hide scroll indicator
https://github.com/user-attachments/assets/0936a631-bae9-45b2-a6d3-78b08cf1e168
[CP-9705]: https://ava-labs.atlassian.net/browse/CP-9705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9705:  token detail bug fix

- packages/core-mobile/app/new/features/track/market/components/MarketGridView.tsx
- packages/core-mobile/app/new/features/track/market/components/MarketListView.tsx
* Fix bug where token list items get shuffled after scrolling. (https://github.com/Shopify/flash-list/issues/855)
https://github.com/user-attachments/assets/584dd390-aa2c-4c6f-adfd-e56390d7b9ca
> Fix bug where token list items get shuffled

- packages/core-mobile/app/new/features/accountSettings/components/About.tsx
- packages/core-mobile/app/new/features/accountSettings/components/AppAppearance.tsx
- packages/core-mobile/app/new/features/accountSettings/components/UserPreferences.tsx
- packages/k2-alpine/src/components/GroupList/GroupList.tsx
* use k2's group list if possible
> use k2 grouplist

- packages/core-mobile/app/hooks/networks/useNetworksListener.ts
- packages/core-mobile/app/new/common/components/BlurViewWithFallback.tsx
- packages/core-mobile/app/new/common/components/BlurredBarsContentLayout.tsx
- packages/core-mobile/app/new/common/components/CollapsibleTabs.tsx
- packages/core-mobile/app/new/common/components/DropdownSelections.tsx
- packages/core-mobile/app/new/common/components/LinearGradientBottomWrapper.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TransactionHistory.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectiblesScreen.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiScreen.tsx
- packages/core-mobile/app/new/features/track/market/components/MarketTokensScreen.tsx
- packages/core-mobile/app/new/features/track/market/hooks/useTrackSortAndView.ts
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/tokenDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/track/index.tsx
- packages/core-mobile/ios/Podfile.lock
- packages/k2-alpine/src/components/Dropdown/SimpleDropdown.tsx
- packages/k2-alpine/src/components/Dropdown/usePopoverAnchor.ts
- packages/k2-alpine/src/components/SegmentedControl/SegmentedControl.tsx
- yarn.lock
various optimizations are added for screens with dropdown and segmented control. please refer to the comments/code.
https://github.com/user-attachments/assets/d516b218-2a63-454d-b697-ec9776f65a1d
> [Perf Improvement] Dropdown and Segmented Control

- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/k2-alpine/src/components/Header/BalanceHeader.tsx
- packages/k2-alpine/src/components/Header/NavigationTitleHeader.tsx
> mask anvigation title header

- packages/core-mobile/app/new/features/onboarding/components/EnterRecoveryPhrase.tsx
- packages/core-mobile/app/new/routes/_layout.tsx
- packages/core-mobile/app/store/app/listeners.ts
- packages/core-mobile/docs/patches.md
- packages/core-mobile/patches/react-native-collapsible-tab-view+8.0.0.patch
please refer to the comments for details
before
https://github.com/user-attachments/assets/6cf10f9f-9225-4d19-a08f-e321b8ba97b6
after
https://github.com/user-attachments/assets/4cd6a06e-93d6-429f-8341-6fadf73be814
> Fix Portfolio being rendered 3 times on app unlocked

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenDetail.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TransactionHistory.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectiblesScreen.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/tokenDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
* Fix minor visual issues with blur header
> Fix minor visual issues

- packages/core-mobile/app/new/common/hooks/usePinOrBiometryLogin.ts
> fix: use await for promise

- packages/core-mobile/app/new/features/stake/components/StakesScreen.tsx
> Fix to rerender cells when changing theme

- packages/k2-alpine/package.json
- packages/k2-alpine/src/components/Slider/Slider.stories.tsx
- packages/k2-alpine/src/components/Slider/Slider.tsx
- packages/k2-alpine/src/components/index.ts
- yarn.lock
**Ticket: [CP-10021]** 
* Implements slider component
https://github.com/user-attachments/assets/58e2ce92-99e0-49ea-abac-2cefc43409e0
[CP-10021]: https://ava-labs.atlassian.net/browse/CP-10021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10021: K2 Slider

- packages/core-mobile/.eslintrc.js
- packages/core-mobile/app/contexts/SwapContext/SwapContext.tsx
- packages/core-mobile/app/contexts/SwapContext/consts.tsx
- packages/core-mobile/app/contexts/SwapContext/performSwap/performSwap.ts
- packages/core-mobile/app/errors/swapError.ts
- packages/core-mobile/app/screens/swap/components/SwapTransactionDetails.tsx
- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/services/swap/SwapService.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/store/posthog/types.ts
- packages/core-mobile/app/utils/basisPointsToPercentage.ts
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-10051]** 
This pr enables swap fee by adding the necessary params when constructing the swap transaction
https://github.com/user-attachments/assets/e16d0da5-e31c-425b-a88f-5a0dc2f71ad2
please retest all the different swaps
[CP-10051]: https://ava-labs.atlassian.net/browse/CP-10051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10051: Enable Swap Fee

- packages/core-mobile/package.json
- yarn.lock
bump bridge unified sdk to 4.0.2 to update bridge warden url
please retest bridge
> Bridge warden url update

- packages/core-mobile/app/new/features/stake/components/Banner.tsx
- packages/core-mobile/app/new/features/stake/components/StakeTokenUnitValue.tsx
- packages/core-mobile/app/new/features/stake/components/StakesScreen.tsx
- packages/core-mobile/app/new/features/stake/utils/index.ts
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/stakeDetail/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/stakeDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/stake/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/_layout.tsx
- yarn.lock
**Ticket: [CP-10160]** 
* Implemented staking detail screen
| Active | Completed |
| --- | --- |
| <img src=https://github.com/user-attachments/assets/f8ba4871-d4d0-49dc-a8fe-22de365c4600 width=320 /> | <img src=https://github.com/user-attachments/assets/d1756eb4-756f-4b82-b550-d9ebaaaa93d8 width=320 /> |
[CP-10160]: https://ava-labs.atlassian.net/browse/CP-10160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10160: Staking Details

- packages/core-mobile/app/new/common/consts/screenOptions.tsx
- packages/core-mobile/app/new/features/accountSettings/components/NotificationToggle.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
- packages/k2-alpine/src/components/Header/NavigationTitleHeader.tsx
- update testnet mode is on design to show just snackbar instead
- fix bugs in https://ava-labs.atlassian.net/browse/CP-10187?focusedCommentId=50373
> Fix settings bug part 2

- packages/k2-alpine/package.json
- packages/k2-alpine/src/components/DateTimePicker/DateTimePicker.stories.tsx
- packages/k2-alpine/src/components/DateTimePicker/DateTimePicker.tsx
- yarn.lock
* Implemented `DateTimePicker` component in k2-alpine
| | light | dark |
| --- | --- | --- |
| iOS | <img src=https://github.com/user-attachments/assets/d0e4f227-02a6-4a0f-b707-2db58140a036 width=320 /> | <img src=https://github.com/user-attachments/assets/a876496b-a166-46c5-bcb6-90d3a90e9133 width=320 /> |
| Android | <img src=https://github.com/user-attachments/assets/474938cf-de7f-425d-8afb-7a2e40ca5a7f width=320 /> | <img src=https://github.com/user-attachments/assets/dc252f03-d141-40f7-b4f5-5e80e8924a57 width=320 /> |
> DateTimePicker

- packages/core-mobile/app/new/features/onboarding/components/VerifyCode.tsx
> Fix verifyCode textInput android focus issue

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
> don't show segmented control for trending tokens

- packages/core-mobile/app/new/common/consts/screenOptions.tsx
- packages/core-mobile/app/new/common/screens/SelectTokenScreen.tsx
- packages/core-mobile/app/new/features/send/screens/SendScreen.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectToken/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectToken/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/send/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/send/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/swap/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/swap/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/_layout.tsx
- packages/core-mobile/docs/patches.md
- packages/core-mobile/patches/@react-navigation+stack+7.1.2.patch
this pr adds a new type of modal in our app. this modal uses the [formsheet](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/formsheet) UX and should be used whenever a modal is on top of another modal.
we are going to use this modal for "Select a Token/Network" screen across the different flows: send, swap, bridge,...
https://github.com/user-attachments/assets/0102530b-882a-4692-8e2e-aff982dadb85
https://github.com/user-attachments/assets/fccc3e17-209c-4ab2-b8b1-56acddbeb062
https://github.com/user-attachments/assets/2d6d6c99-9352-4c7b-95bb-f3f907f661b0
> Stacking Sheets (Form Sheet)

- packages/core-mobile/app/new/common/contexts/ConfettiContext.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/claimStakeReward/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/claimStakeReward/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/stake/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/_layout.tsx
- packages/k2-alpine/package.json
- packages/k2-alpine/src/components/Confetti/Confetti.stories.tsx
- packages/k2-alpine/src/components/Confetti/Confetti.tsx
- packages/k2-alpine/src/components/GroupList/GroupList.tsx
- packages/k2-alpine/src/components/index.ts
- yarn.lock
**Ticket: [CP-10161]** 
* Implemented claiming reward feature for staking.
https://github.com/user-attachments/assets/7282a4d2-6021-41a3-8511-60fd8808ee16
[CP-10161]: https://ava-labs.atlassian.net/browse/CP-10161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10161: Staking flow - Claim reward

- packages/core-mobile/app/new/features/accountSettings/components/AccountButtons.tsx
- packages/core-mobile/app/new/features/accountSettings/components/ContactAddressMenu.tsx
- packages/core-mobile/app/new/routes/_layout.tsx
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
- yarn.lock
- hide export private key
- fix bottom padding issue on android 
- center buttons on login screen
> Hide export private key

- packages/core-mobile/app/new/features/accountSettings/components/AccountItem.tsx
- packages/core-mobile/app/new/features/accountSettings/components/ContactForm.tsx
- packages/core-mobile/app/new/features/accountSettings/components/accountAddresses.tsx
- packages/core-mobile/app/new/features/accountSettings/consts.ts
- packages/core-mobile/app/new/features/accountSettings/utils/constructContactByAddressType.ts
- packages/core-mobile/app/new/features/accountSettings/utils/isValidAddress.ts
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
- packages/core-mobile/app/services/network/consts.ts
- packages/k2-alpine/src/components/AnimatedBalance/AnimatedBalance.tsx
- adjust AccountList, ManageAccount, and AddressBook to use usePrimaryNetworks hook
- update AccountList and ManageAccount to show View Balance when balance is not fetched, and show loading spinner when balance is fetching for the account
https://github.com/user-attachments/assets/eab48f38-7594-4dfb-9790-c81f5b52e7c9
> Adjust account and addressBook

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/tokenDetail/index.tsx
- packages/core-mobile/app/store/balance/slice.ts
- handle explorer link in token detail
- update selectIsBalanceLoadedForAccount to check for matching network and matching isTestnet flag
https://github.com/user-attachments/assets/7e390b6d-3ce7-486f-b5b7-0413f09f7399
https://github.com/user-attachments/assets/ffcf803f-9aca-4546-abc6-dc00475fc44b
> handle explorer link in token detail

- packages/core-mobile/app/hooks/useIsUIDisabled.ts
- packages/core-mobile/app/new/common/components/TokenInputWidget.tsx
- packages/core-mobile/app/new/common/hooks/useErc20ContractTokens.ts
- packages/core-mobile/app/new/common/hooks/useSearchableTokenList.ts
- packages/core-mobile/app/new/features/bridge/screens/BridgeScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
- packages/core-mobile/app/new/features/stake/hooks/useAddStake.ts
- packages/core-mobile/app/new/features/swap/components.tsx/SlippageInput.tsx
- packages/core-mobile/app/new/features/swap/const.ts
- packages/core-mobile/app/new/features/swap/contexts/SwapContext.tsx
- packages/core-mobile/app/new/features/swap/hooks/useNavigateToSwap.ts
- packages/core-mobile/app/new/features/swap/screens/SelectSwapTokenScreen.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/features/swap/store.ts
- packages/core-mobile/app/new/features/swap/utils.ts
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectSwapFromToken/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectSwapFromToken/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectSwapToToken/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/selectSwapToToken/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/swap/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/tokenDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/_layout.tsx
- packages/core-mobile/app/store/balance/slice.ts
- packages/k2-alpine/src/components/Button/Button.tsx
- packages/k2-alpine/src/components/Button/CircularButton.tsx
- packages/k2-alpine/src/utils/colors.ts
**Ticket: [CP-10220]** 
* Implemented swap
https://github.com/user-attachments/assets/e8ed5f54-1a04-40c8-821f-d4a319cf6956
[CP-10220]: https://ava-labs.atlassian.net/browse/CP-10220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10220: Swap

- packages/core-mobile/app/new/features/swap/screens/SelectSwapTokenScreen.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/k2-alpine/src/components/TokenAmountInput/TokenAmountInput.tsx
- packages/k2-alpine/src/components/TokenUnitInput/TokenUnitInput.tsx
**Ticket: [CP-10220]** 
* fixed bugs on Swap
[CP-10220]: https://ava-labs.atlassian.net/browse/CP-10220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Swap - bugfix

- packages/core-mobile/app/new/common/hooks/useSearchableTokenList.ts
> make token prop optional

- packages/core-mobile/app/store/settings/avatar/types.ts
> Small fix for default avatar

- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
* add stake and swap action handers in track token detail screen
> Add missing action handlers in token detail

- packages/core-mobile/app/new/common/utils/sortPrimaryNetworks.ts
- packages/core-mobile/app/new/features/accountSettings/screens/manageNetworks/ManageNetworksScreen.tsx
- packages/core-mobile/app/new/features/bridge/hooks/useBridgeNetworks.ts
- packages/core-mobile/app/new/features/bridge/utils/bridgeUtils.ts
- packages/core-mobile/app/new/features/onboarding/components/EnterRecoveryPhrase.tsx
- packages/core-mobile/app/new/features/onboarding/components/RecoveryPhraseInput.tsx
**Ticket: [CP-10433]** 
* https://ava-labs.atlassian.net/browse/CP-10433
* https://ava-labs.atlassian.net/browse/CP-10429
[CP-10433]: https://ava-labs.atlassian.net/browse/CP-10433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10433: Sort bridge networks + fix bugs

- packages/core-mobile/app/new/features/track/components/SelectionDot.tsx
- packages/core-mobile/app/new/features/track/components/TokenDetailChart.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
* Fix bugs in track token detail screen
> Fix track token detail layout + interactive chart bug

- packages/core-mobile/app/new/features/track/components/ShareFooter.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/share.tsx
* Fix share token screen layout
| before | after |
| --- | --- |
| <img src=https://github.com/user-attachments/assets/4ecc73a7-cedf-43e8-8e13-2a606f2e4229 width=320 /> | <img src=https://github.com/user-attachments/assets/149417a2-a8c3-4f19-ab51-54b5d6a85a64 width=320 /> |
> Fix Share token screen layout

- packages/core-mobile/app/hooks/networks/networkProviderHooks.ts
- packages/core-mobile/app/hooks/networks/useNetworks.ts
- packages/core-mobile/app/hooks/useIsUIDisabled.ts
- packages/core-mobile/app/hooks/useNetworkFee.tsx
- packages/core-mobile/app/new/features/bridge/hooks/useEstimatedReceiveAmount.ts
- packages/core-mobile/app/new/features/track/components/TokenDetailFooter.tsx
- packages/core-mobile/app/store/balance/slice.ts
* Remove some usages of active network
> fix: Remove some usages of active network

- packages/core-mobile/app/new/common/components/HiddenBalanceText.tsx
- packages/core-mobile/app/new/features/accountSettings/components/AccountItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenGridView.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenListView.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/k2-alpine/src/components/AnimatedBalance/AnimatedBalance.tsx
- packages/k2-alpine/src/components/Header/BalanceHeader.tsx
- packages/k2-alpine/src/index.ts
- update privacy mode balance with currrency symbol + ••••••
https://github.com/user-attachments/assets/d69ad186-1cf1-4c22-9d45-ce3ba6f24e48
> Update privacy mode

- packages/core-mobile/app/new/features/onboarding/components/FidoNameInput.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/addRecoveryMethods/(fido)/fidoNameInput.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/addRecoveryMethods/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/addRecoveryMethods/available.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/addRecoveryMethods/index.tsx
**Ticket: [CP-1044]** 
lScreen UI fixes
https://github.com/user-attachments/assets/ee251d8e-7cdb-4566-96e6-6c31e3164bed
> fix recovery methods UI

- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
- packages/core-mobile/app/new/common/components/TokenInputWidget.tsx
- packages/core-mobile/app/new/features/approval/components/NetworkFeeSelector/GasOptions.tsx
- packages/core-mobile/app/new/features/approval/hooks/useNetworkFeeSelector.ts
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
in swap screen:
- auto focus from input 
- remove account row
also make network fee selector use fast fee by default for c-chain (this applies to send/swap/bridge/etc)
auto focus from input
https://github.com/user-attachments/assets/555941c9-a0e9-4d68-af57-8db1e5dbd539
use fast fee for c-chain
https://github.com/user-attachments/assets/a93c7b2b-f78e-4f2a-92f0-b4fee340c7ae
> Swap improvements

- packages/core-mobile/app/new/features/receive/components/AccountAddresses.tsx
> fix xp address on copy

- packages/core-mobile/app/new/features/stake/components/NodeItem.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/addStake/selectNode.tsx
> fix node screen ui

- packages/core-mobile/app/new/common/utils/sortPrimaryNetworks.ts
- packages/core-mobile/app/new/features/onboarding/components/VerifyRecoveryPhrase.tsx
- packages/core-mobile/app/store/network/slice.ts
**Ticket: [CP-10355]** 
Add bitcoin and eth as enabled all the time
[CP-10355]: https://ava-labs.atlassian.net/browse/CP-10355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add bitcoin and eth as alwaysEnabledNetworks

- packages/core-mobile/app/new/common/components/Logo.tsx
- packages/core-mobile/app/new/common/components/TokenLogo.tsx
- packages/core-mobile/app/new/features/approval/components/BalanceChange/BalanceChange.tsx
- packages/core-mobile/app/new/features/approval/components/BalanceChange/TokenDiffGroup.tsx
- packages/core-mobile/app/new/features/approval/components/NetworkFeeSelectorWithGasless.tsx
- packages/core-mobile/app/new/features/approval/components/SpendLimits/SpendLimits.tsx
- packages/core-mobile/app/new/features/approval/screens/ApprovalScreen.tsx
- make balance change smaller
- add missing spend limit banner
- adjust gasless copy
- adjust token logo for nft
token nft logo
spend limit
https://github.com/user-attachments/assets/dc5bfec0-f251-4c1b-b550-6c96eaef4bc8
> Approval improvements

- packages/core-mobile/app/new/features/browser/BrowserContext.tsx
**Ticket: [CP-10491]** 
[CP-10491]: https://ava-labs.atlassian.net/browse/CP-10491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10491: cannot navigate in browser

- packages/core-mobile/app/new/features/onboarding/components/VerifyRecoveryPhrase.tsx
* fix recovery phrase layout to match the design
> Fix recovery phrase layout

- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleDetailsContent.tsx
**Ticket: [CP-10508]** 
- convert object to array
[CP-10508]: https://ava-labs.atlassian.net/browse/CP-10508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10508: handle object attributes

- packages/core-mobile/app/new/common/hooks/useSearchableTokenList.ts
- packages/core-mobile/app/new/features/bridge/hooks/useAssetBalances.ts
- packages/core-mobile/app/store/balance/slice.ts
**Ticket: [CP-10426:]** 
https://github.com/user-attachments/assets/130909c6-93cf-4caa-b4a8-4c50ea5f18f3
> Hide disabled network tokens

- packages/core-mobile/app/new/features/buy/screens/BuyScreen.tsx
Ticket: [CP-10354]
[CP-10354]: https://ava-labs.atlassian.net/browse/CP-10354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10354: make coinbase pay open external browser

- packages/core-mobile/app/new/features/accountSettings/components/About.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
**Ticket: [CP-10496]** 
* call back() before moving to the browser from settings
https://github.com/user-attachments/assets/afd17f86-476a-40cd-96c4-64ba2c9647ca
[CP-10496]: https://ava-labs.atlassian.net/browse/CP-10496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10496: Fix no response with the setting icon in Android

- packages/core-mobile/app/new/common/hooks/useModalScreenOptions.tsx
- packages/core-mobile/app/new/common/utils/stackModalInterpolator.ts
https://github.com/user-attachments/assets/f54581e2-3bad-4e28-a65c-644cbe60b0e0
> use horizontal card transition

- packages/core-mobile/app/new/features/accountSettings/screens/addressBook/AddContactScreen.tsx
**Ticket: [CP-10452]** 
- Fixed adding avatar on new contact 
- Reset the avatar when unmounting
https://github.com/user-attachments/assets/b13fefdb-00fd-4e1e-9c82-5eb4334df54c
[CP-10452]: https://ava-labs.atlassian.net/browse/CP-10452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug: New contact avatar

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/connectedSites.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/securityAndPrivacy.tsx
Added "Disconnect all" button back to connectedSites
https://github.com/user-attachments/assets/ba033aea-5abc-473a-9468-f06f51eedc7a
> Connected websites disconnect all button

- packages/core-mobile/app/seedless/services/wallet/SeedlessWallet.ts
**Ticket: [CP-10524]** 
[CP-10524]: https://ava-labs.atlassian.net/browse/CP-10524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10524: use eip191Sign for seedless evm message signing

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/track/market/components/FavoriteScreen.tsx
- packages/core-mobile/app/new/features/track/market/components/MarketScreen.tsx
- packages/core-mobile/app/new/features/track/trending/components/TrendingScreen.tsx
Added the same first load animation for 
Portfolio => Assets
Track => Trending/Favorites/Market
https://github.com/user-attachments/assets/b0c6eb00-62db-492d-9d77-912b39cd7138
> Lists first load animation

- packages/core-mobile/app/new/common/components/ActionSheet.tsx
- packages/core-mobile/app/new/features/accountSettings/components/accountAddresses.tsx
- packages/core-mobile/app/new/features/portfolio/assets/screens/TokenDetailScreen.tsx
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
fix back button not actually rejecting transaction request
fix copy button layout
add go back to places where we open browser to prevent render issue
> Fix a few bugs

- packages/core-mobile/app/new/common/components/SelectAvatar.tsx
- packages/core-mobile/app/new/common/hooks/usePinOrBiometryLogin.ts
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
**Ticket: [CP-10544]** 
Fixed keyboard opening while login with biometry is happening
[CP-10544]: https://ava-labs.atlassian.net/browse/CP-10544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug: Biometry keyboard open 

- packages/core-mobile/app/new/features/collectibleSend/screens/ScanQrCodeScreen.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleManagementScreen.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/hooks/useCollectiblesFilterAndSort.ts
- packages/core-mobile/app/store/balance/types.ts
https://github.com/user-attachments/assets/3895c85c-6d34-489e-9445-3e795ce586fe
> Fix multi select on collectible filter

- packages/core-mobile/app/hooks/watchlist/useGetPrices.ts
- packages/core-mobile/app/hooks/watchlist/useWatchlist.ts
- packages/core-mobile/app/new/features/track/components/ShareChart.tsx
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
- packages/core-mobile/app/services/watchlist/WatchlistService.ts
**Ticket: [CP-10536]** 
https://github.com/user-attachments/assets/fc9790a9-aed9-414f-b32b-2855b5e26bc6
[CP-10536]: https://ava-labs.atlassian.net/browse/CP-10536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10536: fetch non-top-token prices

- packages/core-mobile/app/store/account/listeners.ts
**Ticket: [CP-10556]** 
we were calling reload accounts twice one after another and one of them had the wrong active chain id which messed up everything. this pr makes sure we are only calling reload once and also remove the dependence on active network
https://github.com/user-attachments/assets/9663c427-aeda-4add-814b-38aaa46539a2
[CP-10556]: https://ava-labs.atlassian.net/browse/CP-10556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10556: Fix testnet addresses not updating after developer mode is toggled for seedless

- packages/k2-alpine/src/components/Animated/AnimatedPressable.tsx
Switched to onTouchEnd instead of onPressOut for resetting animation
Lowered the threshold for resetting to 1px instead of 2px for cancelling x,y axis movement
> Refactored AnimatedPressable

- packages/core-mobile/app/new/features/portfolio/collectibles/hooks/useCollectiblesFilterAndSort.ts
- packages/core-mobile/app/services/nft/utils.ts
* Sort nfts by lastUpdatedTimestamp when DateAdded option is selected
> Sort nfts by lastUpdatedTimestamp when DateAdded option is selected

- packages/core-mobile/app/new/common/components/ActionSheet.tsx
- packages/core-mobile/app/new/features/collectibleSend/screens/RecentContactsScreen.tsx
- packages/core-mobile/app/new/features/collectibleSend/screens/ScanQrCodeScreen.tsx
**Ticket: [CP-10542]** 
- fix back button to reject on android
- use local isSending state in component
[CP-10542]: https://ava-labs.atlassian.net/browse/CP-10542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10542: Action sheet fix for android

- packages/core-mobile/app/new/features/approval/components/ActionButtons.tsx
- packages/core-mobile/app/new/features/approval/screens/ApprovalScreen/ApprovalScreen.tsx
https://github.com/user-attachments/assets/0a87599b-6378-48d3-935c-dc391c55d579
> add spinner to approval

- packages/core-mobile/app/new/common/components/ContactList.tsx
- packages/core-mobile/app/new/common/components/ScreenHeader.tsx
- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
- packages/core-mobile/app/new/features/accountSettings/components/ContactForm.tsx
- packages/core-mobile/app/new/features/buy/screens/BuyScreen.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiGridView.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiScreen.tsx
- packages/core-mobile/app/new/features/send/components/RecentContacts.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/defiDetail/index.tsx
- packages/core-mobile/app/utils/openInAppBrowser.ts
- packages/core-mobile/app/utils/openInSystemBrowser.test.ts
- packages/core-mobile/app/utils/openInSystemBrowser.ts
**Ticket: [CP-10587]** 
long text handling
defi 
https://github.com/user-attachments/assets/44018f47-8241-4282-8938-0b4744ddec67
[CP-10584]: https://ava-labs.atlassian.net/browse/CP-10584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-10587]: https://ava-labs.atlassian.net/browse/CP-10587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> a few contact, select avatar and defi adjustments

- packages/core-mobile/app/new/common/components/ListScreen.tsx
- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
- packages/core-mobile/app/new/common/components/SelectAvatar.tsx
- packages/core-mobile/app/new/common/components/VerifyWithPinOrBiometry.tsx
- packages/core-mobile/app/new/common/hooks/useFadingHeaderNavigation.tsx
- packages/core-mobile/app/new/features/onboarding/components/AddRecoveryMethods.tsx
- packages/core-mobile/app/new/features/onboarding/components/AnalyticsConsent.tsx
- packages/core-mobile/app/new/features/onboarding/components/Confirmation.tsx
- packages/core-mobile/app/new/features/onboarding/components/CreatePin.tsx
- packages/core-mobile/app/new/features/onboarding/components/EnterRecoveryPhrase.tsx
- packages/core-mobile/app/new/features/onboarding/components/FidoNameInput.tsx
- packages/core-mobile/app/new/features/onboarding/components/RecoveryPhrase.tsx
- packages/core-mobile/app/new/features/onboarding/components/SetWalletName.tsx
- packages/core-mobile/app/new/features/onboarding/components/TermsAndConditions.tsx
- packages/core-mobile/app/new/features/onboarding/components/VerifyCode.tsx
- packages/core-mobile/app/new/features/onboarding/components/VerifyRecoveryPhrase.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
- packages/core-mobile/app/new/routes/forgotPin.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/selectMfaMethod.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/verifyCode.tsx
**Ticket: [CP-10588]** 
- adjust navigation title
- remove not-found route, so navigating unmatched route does nothing
- remove navigation title where showNavigationHeaderTitle is false
- add spinner to confirmation footer button since initializing the wallet can take some time
[CP-10588]: https://ava-labs.atlassian.net/browse/CP-10588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10588: Re-enable page control

- packages/core-mobile/app/new/routes/_layout.tsx
> remove not found route

- packages/core-mobile/app/new/routes/+not-found.tsx
- packages/core-mobile/app/new/routes/_layout.tsx
> Add +not-found route

- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleItem.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleRenderer.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/hooks/useNfts.ts
- packages/core-mobile/app/new/features/portfolio/collectibles/screens/CollectibleDetailsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/screens/CollectibleManagementScreen.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/screens/CollectiblesScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/collectibleDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/collectibleManagement/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
- packages/k2-alpine/src/components/Video/Video.tsx
…loperMode
**Ticket: [CP-10572]** 
**Ticket: [CP-10471]** 
[CP-10572]: https://ava-labs.atlassian.net/browse/CP-10572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-10471]: https://ava-labs.atlassian.net/browse/CP-10471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Collectible fixes

- packages/core-mobile/app/screens/summitLondon2025/MintNftScreen.tsx
**Ticket: [CP-10316]** 
* fix minor UI issues.
[CP-10316]: https://ava-labs.atlassian.net/browse/CP-10316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10316: Fix UI issues

- packages/core-mobile/app/new/common/utils/sortTokensWithPrimaryFirst.ts
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
- packages/core-mobile/app/new/features/send/screens/SelectSendTokenScreen.tsx
**Ticket: [CP-10448]** 
* Fix sort in portfolio assets screen
[CP-10448]: https://ava-labs.atlassian.net/browse/CP-10448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10448: Fix sort in portfolio assets screen

- packages/core-mobile/app/new/features/send/components/RecentContacts.tsx
- packages/core-mobile/app/new/features/send/screens/RecentContactsScreen.tsx
- packages/core-mobile/app/new/features/send/utils/getAddressByChainId.test.ts
- packages/core-mobile/app/new/features/send/utils/getAddressByChainId.ts
**Ticket: [CP-10473]** 
- show correct address in RecentContactScreen based on chain
https://github.com/user-attachments/assets/ca6c3221-bf50-4360-a5f1-c512a786c1ae
[CP-10473]: https://ava-labs.atlassian.net/browse/CP-10473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10473: show correct address in recentContact screen

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
**Ticket: [CP-10447]** 
https://github.com/user-attachments/assets/8825b132-8854-4e7d-9064-311e0f3853e8
[CP-10447]: https://ava-labs.atlassian.net/browse/CP-10447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10447: check isLoading on AssetScreen

- packages/core-mobile/app/new/features/accountSettings/components/AccountItem.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/account.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/index.tsx
**Ticket: [CP-10570]** 
[CP-10570]: https://ava-labs.atlassian.net/browse/CP-10570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10570: Show empty amount on accountsList

- packages/core-mobile/app/new/features/accountSettings/utils/isValidAddress.test.ts
- packages/core-mobile/app/new/features/accountSettings/utils/isValidAddress.ts
- packages/core-mobile/app/new/features/accountSettings/utils/isValidAddressByVmName.ts
- packages/core-mobile/app/new/features/send/components/SendToken.tsx
- packages/core-mobile/app/new/features/send/context/sendContext.tsx
- packages/core-mobile/app/new/features/send/screens/RecentContactsScreen.tsx
- packages/core-mobile/app/new/features/send/screens/ScanQrCodeScreen.tsx
- packages/core-mobile/app/new/features/send/screens/SendScreen.tsx
- packages/core-mobile/app/new/features/send/utils/getNetworks.ts
**Ticket: [CP-10549]** 
- always pass in isDeveloperMode to isValidAddress to make sure address validates correct for mainnet and testnet.
[CP-10549]: https://ava-labs.atlassian.net/browse/CP-10549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10549: Fix unable to send p-chain token on testnet

- packages/core-mobile/app/new/features/portfolio/assets/screens/TokenDetailScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
> hide 0 amount part 2

- packages/core-mobile/app/new/features/accountSettings/context/RecoverMethodsProvider.tsx
- packages/core-mobile/app/new/features/onboarding/components/FidoNameInput.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/addRecoveryMethods/(fido)/fidoNameInput.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/(fido)/fidoNameInput.tsx
- packages/k2-alpine/src/components/Button/Button.tsx
* https://ava-labs.atlassian.net/browse/CP-10348
* https://ava-labs.atlassian.net/browse/CP-10646
> CP-10646: remove unnecessary back() + fix button background color issue

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenDetail.tsx
**Ticket: [CP-10580]** 
[CP-10580]: https://ava-labs.atlassian.net/browse/CP-10580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10580: show token value in selected currency

- packages/core-mobile/app/new/common/components/NavigationRedirect.tsx
- yarn.lock
**Ticket: [CP-10672]** 
[CP-10672]: https://ava-labs.atlassian.net/browse/CP-10672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10672: just exit with no alert on Android

- packages/core-mobile/app/new/features/track/trending/components/TrendingTokenListView.tsx
> Add view button to trending tokens with no buy button

- packages/core-mobile/app/new/features/tokenManagement/screens/AddCustomTokenScreen.tsx
- packages/core-mobile/app/resources/Constants.ts
- packages/core-mobile/app/store/rpc/handlers/avalanche_getAddressesInRange/avalanche_getAddressesInRange.ts
- packages/core-mobile/app/utils/getAddressesInRange.ts
**Ticket: [CP-10658]** 
- cache addressesInRange response for 30 minutes
- reset token address and network on add custom token screen open
[CP-10658]: https://ava-labs.atlassian.net/browse/CP-10658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10658: Cache avalanche_getAddressesInRange 

- packages/core-mobile/app/new/common/utils/isValidContactName.ts
- packages/core-mobile/app/new/features/accountSettings/components/ContactForm.tsx
- packages/core-mobile/app/new/features/tokenManagement/screens/AddCustomTokenScreen.tsx
**Ticket: [CP-10651]** 
- remove regex check on contact name
- show default value for contact name input, to make it easier to edit
[CP-10651]: https://ava-labs.atlassian.net/browse/CP-10651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10651: Allow any character for contact name

- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
**Ticket: [CP-10679]** 
* Fix swap validation bug
[CP-10679]: https://ava-labs.atlassian.net/browse/CP-10679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10679: Fix swap validation bug

- packages/core-mobile/app/contexts/SwapContext/performSwap/performSwap.ts
**Ticket: [CP-10675]** 
[CP-10675]: https://ava-labs.atlassian.net/browse/CP-10675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10675: Account for partnerFeeBPS for swap tx

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenManagementItem.tsx
- packages/core-mobile/app/new/features/tokenManagement/screens/TokenManagementScreen.tsx
**Ticket: [CP-10399]** 
* fixed to include native tokens in manage token list screen
[CP-10399]: https://ava-labs.atlassian.net/browse/CP-10399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10399: Show native tokens in manage token list

- packages/core-mobile/app/new/features/onboarding/components/Confirmation.tsx
* Revert blur effect for Avatar in onboarding confirmation on iOS
> Revert blur effect for Avatar in onboarding confirmation on iOS

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItem.tsx
> fix amount parsing in tx history item

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/store/balance/listeners.ts
https://github.com/user-attachments/assets/97322b6e-5424-4ff2-a981-d95e1fd4d561
> Prefetch networks before balance fetching

- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
- packages/core-mobile/app/new/features/accountSettings/components/AdvancedField.tsx
- packages/core-mobile/app/new/features/onboarding/components/Confirmation.tsx
- packages/core-mobile/app/new/features/onboarding/components/SetWalletName.tsx
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
Fixes:
- ScrollScreen footer fixes for correct contentContainerStyle paddings
- pin screen positioning when keyboard is open
- confirmation screen positioning
**Confirmation + Create PIN** 
Old
https://github.com/user-attachments/assets/3c81c2be-4222-48cf-b0f0-20dda55f46c8
New
https://github.com/user-attachments/assets/1a926bfb-e58c-49cf-a2ad-ca1e4b97fe8c
**PIN**
Old
https://github.com/user-attachments/assets/7494eafc-ea35-4517-9c58-e57eb362b5a4
New
https://github.com/user-attachments/assets/bb5cf94a-a265-46b7-9b3d-6dce6e8be5b1
> fix scrollable + pin input + confirmation

- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiGridView.tsx
**Ticket: [CP-10590]** 
* Replaced `AnimatedPressable` with `TouchableOpacity` to fix event propagation issue
[CP-10590]: https://ava-labs.atlassian.net/browse/CP-10590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10590: Fix browser tab navigation handling in DeFi screen

- packages/core-mobile/app/new/features/portfolio/assets/screens/TokenDetailScreen.tsx
**Ticket: [CP-10699]** 
*  Pre-fill from/to token when initiated from Token Detail screen
[CP-10699]: https://ava-labs.atlassian.net/browse/CP-10699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10699: Swap – Pre-fill from/to token when initiated from Token Detail screen

- packages/core-mobile/app/new/features/accountSettings/components/AdvancedField.tsx
- packages/core-mobile/app/new/features/accountSettings/components/ContactForm.tsx
> add qr code validation for address

- packages/core-mobile/app/new/common/utils/sortTokensWithPrimaryFirst.ts
- packages/core-mobile/app/new/features/send/screens/SelectSendTokenScreen.tsx
* https://ava-labs.atlassian.net/browse/CP-10720
> CP-10720: show native token on L2 network in send form

- .github/CODEOWNERS
- packages/core-mobile/app/hooks/networks/useGetNetworks.ts
- packages/core-mobile/app/hooks/networks/useNetworkContractTokens.ts
- packages/core-mobile/app/new/common/hooks/useCChainContractTokens.ts
- packages/core-mobile/app/new/common/hooks/useEthereumContractTokens.ts
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
**Ticket: [CP-10768]** 
[CP-10768]: https://ava-labs.atlassian.net/browse/CP-10768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10768: Handle long track token's website

- packages/core-mobile/app/services/nft/NftProcessor.ts
**Ticket: [CP-10764]** 
[CP-10764]: https://ava-labs.atlassian.net/browse/CP-10764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10764: process metadata only if ipfs response is successful

- packages/core-mobile/app/new/common/components/SubTextNumber.tsx
- packages/core-mobile/app/new/common/components/TokenHeader.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenGridView.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenListView.tsx
- packages/core-mobile/app/utils/formatNumber/formatNumber.ts
- packages/core-mobile/app/utils/numberToSubscriptFormat/numberToSubscriptFormat.test.ts
- packages/core-mobile/app/utils/numberToSubscriptFormat/numberToSubscriptFormat.ts
**Ticket: [CP-10774]** 
[CP-10774]: https://ava-labs.atlassian.net/browse/CP-10774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10774: Use SubTextNumber

- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
**Ticket: [CP-10787]** 
[CP-10787]: https://ava-labs.atlassian.net/browse/CP-10787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enter pin screen - remove the biometrics button when the spinner is visible

- packages/core-mobile/app/new/features/track/components/SparklineChart.tsx
- packages/core-mobile/app/new/features/track/components/TokenDetailChart.tsx
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
**Ticket: [CP-10765]** 
Features
- formatted currency on chart
- visible when touching
https://github.com/user-attachments/assets/684b4250-c408-4d51-b3ad-b010d4b4f467
[CP-10765]: https://ava-labs.atlassian.net/browse/CP-10765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10765 - Add axis labels on graphs

- packages/core-mobile/app/seedless/services/wallet/transformKeyInfosToPubkeys.ts
> Make Solana session key optional in Seedless flow

- packages/core-mobile/app/new/features/approval/hooks/useNetworkFeeSelector.ts
- packages/core-mobile/app/new/features/approval/types.ts
**Ticket: [CP-11042]** 
Changed labels
[CP-11042]: https://ava-labs.atlassian.net/browse/CP-11042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11042 Change gas widget labels

- packages/core-mobile/app/new/common/hooks/useImportMnemonic.ts
**Ticket: [CP-10838](https://ava-labs.atlassian.net/browse/CP-10838)** 
// will put in jira ticket to avoid showing recovery phrase
manually tested with seedless / mnemonic wallets 
[CP-10838]: https://ava-labs.atlassian.net/browse/CP-10838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10838: import recovery phrase navigation fix 

- packages/core-mobile/app/new/features/buyOnramp/hooks/useSearchDefaultsByCountry.ts
- packages/core-mobile/app/new/features/buyOnramp/hooks/useSearchPaymentMethods.ts
- packages/core-mobile/app/new/features/buyOnramp/screens/BuyTokenScreen.tsx
> update network logo borderColor

- packages/core-mobile/app/hooks/networks/useNetworks.ts
- packages/core-mobile/app/seedless/services/wallet/SeedlessWallet.ts
- packages/core-mobile/app/services/account/AccountsService.tsx
- packages/core-mobile/app/services/earn/EarnService.ts
- packages/core-mobile/app/services/wallet/MnemonicWallet.ts
- packages/core-mobile/app/services/wallet/PrivateKeyWallet.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
- packages/core-mobile/app/services/wallet/types.ts
- packages/core-mobile/app/store/account/listeners.ts
- packages/core-mobile/app/store/account/thunks.ts
- packages/core-mobile/app/store/balance/slice.ts
- packages/core-mobile/app/store/notifications/listeners/scheduleNotificationsForActiveStakesPeriodically.ts
- packages/core-mobile/app/store/wallet/thunks.ts
- packages/core-mobile/app/utils/publicKeys.ts
- packages/core-mobile/app/vmModule/ApprovalController/ApprovalController.ts
- packages/core-mobile/app/vmModule/ModuleManager.ts
**Ticket: [CP-11167]** 
1. Network Parameter Simplification
* Replaced Network objects with isTestnet: boolean across multiple services
* Files affected: AccountsService.tsx, EarnService.ts, WalletService.tsx, and various store files
* This simplifies the API by only passing the essential testnet flag instead of full network objects
2. Standardized getPublicKeyFor Method Interface
* Changed method signature from getPublicKeyFor(path: string, curve: Curve) to getPublicKeyFor({ derivationPath?, curve }: {...})
* Implemented across all wallet types: SeedlessWallet, MnemonicWallet, PrivateKeyWallet
* Added validation to ensure derivationPath is provided when required
* Enhanced PrivateKeyWallet to support both SECP256K1 and ED25519 curves
3. Removed Active Network Dependencies
* Removed …
> CP-11167: Derive p/x and Solana addresses for PrivateKeyWallet + refactoring

- packages/core-mobile/app/new/common/components/WalletCard.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/k2-alpine/src/components/Button/Button.tsx
- packages/k2-alpine/src/components/Button/FilterButton.tsx
- packages/k2-alpine/src/utils/colors.ts
- Fixed button disabled state to be based off opacity on the entire element rather than it's background.
- Fixed WalletCard touch areas and truncated text
https://github.com/user-attachments/assets/1993339f-9cb2-42a9-a842-331a1e6d0e2e
> Fix disabled button UI + WalletCard touch area

- packages/core-mobile/app/new/common/hooks/useManageWallet.ts
- packages/core-mobile/app/new/features/accountSettings/components/AccountButtons.tsx
**Ticket: [CP-11161]** 
* Remove unnecessary text field in account renaming alert 
[CP-11161]: https://ava-labs.atlassian.net/browse/CP-11161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11161: remove unnecessary input field in account renaming

- packages/core-mobile/app/new/features/accountSettings/utils/getAddressFromContact.ts
**Ticket: [CP-11072](https://ava-labs.atlassian.net/browse/CP-11072)** 
https://github.com/user-attachments/assets/383b20f6-9590-40c7-af47-5ef55c45dbad
Manually tested in app (see video above)
[CP-11072]: https://ava-labs.atlassian.net/browse/CP-11072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11072: Show contacts address for solana 

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/changePin.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/verifyChangePin.tsx
- packages/core-mobile/ios/Podfile.lock
- yarn.lock
**Ticket: [CP-11340]** 
- add navigation back for change pin
- add missing enableBiometry call when useBiometrics is enabled
[CP-11340]: https://ava-labs.atlassian.net/browse/CP-11340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11340: fix change pin flow

- packages/core-mobile/app/new/features/accountSettings/components/AccountButtons.tsx
**Ticket: [CP-11265]** 
[CP-11265]: https://ava-labs.atlassian.net/browse/CP-11265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11265: update copy

- packages/core-mobile/app/new/common/components/WalletCard.tsx
- packages/core-mobile/app/new/common/hooks/useManageWallet.ts
**Ticket: [CP-11287]** 
* Refactor wallet card by passing wallet object instead of wallet id
[CP-11287]: https://ava-labs.atlassian.net/browse/CP-11287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Wallet card refactoring

- packages/core-mobile/app/new/common/hooks/useSearchableTokenList.ts
- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/services/balance/BalanceService.ts
- packages/core-mobile/app/store/balance/listeners.ts
- packages/core-mobile/app/store/balance/slice.ts
- packages/core-mobile/app/store/balance/types.ts
**Ticket: [CP-11045]** 
In case the request fails for tokens with balance, display "Oops, something went wrong" message. 
https://github.com/user-attachments/assets/d599ef97-31d6-4d00-92e7-f5df1fb2a17e
[CP-11045]: https://ava-labs.atlassian.net/browse/CP-11045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11045 - If Glacier 500s show "Oops" screen and balance incomplete warning

- packages/core-mobile/app/store/account/listeners.ts
…esses
**Ticket: [CP-11388](https://ava-labs.atlassian.net/browse/CP-11388)** 
Infinite loop bug: When using a seedless wallet with Solana feature flag disabled, the app got stuck in an endless loop showing "Updating accounts..." toast.
Root cause: The code was checking for missing Solana addresses (!account.addressSVM) and attempting to derive them, but since Solana support was disabled, accounts would never get Solana addresses. This created a cycle:
Check for missing Solana addresses 
Derive missing keys via API call
Reload accounts (still no Solana addresses because feature is off)
Repeat step 1 → infinite loop
Added `selectIsSolanaSupportBlocked` feature flag check before attempting to derive missing Solana keys in both:
`initAccounts()` - during account initialization …
> Bug: CP-11388: Prevent Infinite loop of deriveMissingAddresses when solana FF is OFF

- packages/core-mobile/app/new/common/components/WalletCard.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
**Ticket: [CP-11395]** 
Refactored ScrollScreen for a ListScreen to handle gestures using flashlist
https://github.com/user-attachments/assets/c21fba3e-c836-4bc5-b64e-70d6f5381c9a
[CP-11395]: https://ava-labs.atlassian.net/browse/CP-11395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11395 - [Android Import PK Seedless] Unable to scroll the account list

- packages/core-mobile/app/new/features/meld/onramp/screens/SelectBuyAmountScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/AvaxLogoGradientSvg.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
- packages/core-mobile/app/new/features/portfolio/screens/PortfolioScreen.tsx
- packages/core-mobile/app/store/balance/slice.ts
- packages/k2-alpine/src/components/Header/BalanceHeader.tsx
https://github.com/user-attachments/assets/4a88800f-0629-4127-bf8d-f29e60cd15c2
> fix portfolio loading state

- packages/core-mobile/app/hooks/networks/useTokenList.ts
- packages/core-mobile/app/services/activity/ActivityService.tsx
- packages/core-mobile/app/store/rpc/listeners/index.test.ts
- packages/core-mobile/app/vmModule/utils/mapToVmNetwork.ts
…fore mapping to vm
**Ticket: [CP-11322](https://ava-labs.atlassian.net/browse/CP-11322)** 
https://github.com/user-attachments/assets/c173cdcc-6c84-4b10-94c8-92a220c4dd9b
Manually Tested with XT
- Imported private key from Mobile Wallet into XT so I could confirm matching activity on both, as seen above in the videos. 
[CP-11322]: https://ava-labs.atlassian.net/browse/CP-11322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11322: Show Solana SPL token activity on Token Details 

- packages/core-mobile/app/new/features/meld/hooks/useSelectAmount.tsx
> fix offramp incorrect amount validation logic

- packages/core-mobile/app/new/common/hooks/useContacts.ts
**Ticket: [CP-11486](https://ava-labs.atlassian.net/browse/CP-11486)** 
**Ticket: [CP-11487](https://ava-labs.atlassian.net/browse/CP-11487)** 
https://github.com/user-attachments/assets/c6f7a5c5-c614-4e08-a706-d92e8f409198
- Manually tested as seen above in the video. 
[CP-11486]: https://ava-labs.atlassian.net/browse/CP-11486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-11487]: https://ava-labs.atlassian.net/browse/CP-11487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> CP-11486: Update useContacts to include SVM address

- packages/core-mobile/app/new/features/swap/consts.ts
- packages/core-mobile/app/new/features/swap/contexts/SwapContext.tsx
- packages/core-mobile/app/new/features/swap/providers/ParaswapProvider.ts
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/features/swap/types.ts
**Ticket: [[CP-11478](https://ava-labs.atlassian.net/browse/CP-11478) + [CP-11549](https://ava-labs.atlassian.net/browse/CP-11549)]** 
https://github.com/user-attachments/assets/e59c8ac5-bc5f-4a99-8426-84e8407d6aef
[CP-11478]: https://ava-labs.atlassian.net/browse/CP-11478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-11549]: https://ava-labs.atlassian.net/browse/CP-11549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add auto-refresh for swap page, show deducted amount after fees

- packages/core-mobile/app/new/features/approval/components/SpendLimits/SpendLimitOptions.tsx
- packages/core-mobile/app/new/features/approval/hooks/useNetworkFeeSelector.ts
- packages/core-mobile/app/new/features/swap/components.tsx/SlippageInput.tsx
- packages/k2-alpine/src/components/FiatAmountInputWidget/FiatAmountInput.tsx
- packages/k2-alpine/src/components/TokenUnitInput/TokenUnitInput.tsx
- packages/k2-alpine/src/utils/tokenUnitInput.test.ts
replaced "," with "." in all token / fiat / decimal based inputs 
https://github.com/user-attachments/assets/d736ed78-26dd-4f2a-9fdd-60162dc41141
https://github.com/user-attachments/assets/abb582f7-1276-4f77-b5cc-29876bc31da0
https://github.com/user-attachments/assets/566807e8-1e78-420c-8d17-2d70090a9778
https://github.com/user-attachments/assets/46c7da6b-97f3-426b-b726-144644fb3a55
https://github.com/user-attachments/assets/c2ae097e-047e-4866-b4b4-74dceb92cbe2
Manual testing as seen in videos above
> replace commas with decimals in decimal type inputs

- packages/core-mobile/app/new/features/onboarding/store.ts
- packages/core-mobile/app/new/routes/onboarding/seedless/createPin.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/setWalletName.tsx
- packages/core-mobile/app/store/account/listeners.ts
- packages/core-mobile/app/store/account/slice.ts
- yarn.lock
> solana address fix in account selector

- packages/core-mobile/app/new/features/portfolio/screens/PortfolioScreen.tsx
- checks infinity/NaN for percent change in BalanceHeader using `isFinite`
> check if percent change is infinity

- packages/core-mobile/app/new/routes/onboarding/mnemonic/confirmation.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/selectAvatar.tsx
- packages/core-mobile/app/new/routes/onboarding/mnemonic/setWalletName.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/confirmation.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/selectAvatar.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/setWalletName.tsx
**Ticket: [CP-11599]** 
- add useDebounceCallback to prevent screen index increment more than once when button is rapidly pressed.
[CP-11599]: https://ava-labs.atlassian.net/browse/CP-11599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11599: use useDebounceCallback for onboarding buttons

- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/_layout.tsx
**Ticket: [CP-11602]** 
Move the tab at the end.
[CP-11602]: https://ava-labs.atlassian.net/browse/CP-11602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11602 - move activity tab to the end

- packages/core-mobile/app/new/routes/onboarding/mnemonic/createPin.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/createPin.tsx
…ysical device
**Ticket: [CP-11581](https://ava-labs.atlassian.net/browse/CP-11581)** 
duplicated error by turning off face id on the physical device 
tested recovery phrase / create new wallet with mnemonic 
Wallet deleted immediately after testing
https://github.com/user-attachments/assets/8320e043-5ac9-4f83-a152-73e6bf2ed642
https://github.com/user-attachments/assets/186c4ba9-14d5-4b08-b285-8fccd4050be6
https://github.com/user-attachments/assets/3d0e81f3-5430-4e99-a737-dfb61f8c18fa
[CP-11581]: …
> CP-11581: Fix Set Pin Bug in onboarding with biometrics off 

- packages/core-mobile/app/new/features/approval/components/SpendLimits/SpendLimits.tsx
> fix spend limit spacing

- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/portfolio/_layout.tsx
Added check for opening solana launch modal if feature is enabled.
> add feature flag for solana launch modal

- packages/core-mobile/app/new/features/activity/hooks/useActivityFilterAndSearch.ts
- packages/core-mobile/app/new/features/activity/utils.ts
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItemTitle.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TransactionHistory.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useTokenDetailFilterAndSort.ts
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleFetchAndRender.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleRenderer.tsx
**Ticket: [CP-11656]** 
Includes
- nft transaction title and subtitle fix
- loading nft asset
- displaying nfts on `TokenDetailsScreen`
- add "NFT" filter for AVAX and ETH
https://github.com/user-attachments/assets/968af2a6-9724-4163-a43a-81b4c14915a2
https://github.com/user-attachments/assets/4ec1faac-8c51-44fa-9a4c-ff7b8cca485a
[CP-11656]: https://ava-labs.atlassian.net/browse/CP-11656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11656 - GA - Display NFT transaction properly

- packages/core-mobile/app/new/features/approval/components/BalanceChange/TokenDiffGroup.tsx
**Ticket: [CP-11721](https://ava-labs.atlassian.net/browse/CP-11721)** 
https://github.com/user-attachments/assets/c8812509-de0b-40a2-8b18-4da708eee5fb
https://github.com/user-attachments/assets/16672112-dc69-45b2-afb7-81e8cd4041d8
- manually tested in different locales 
[CP-11721]: https://ava-labs.atlassian.net/browse/CP-11721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11721: Local Currency Formatting fixes on Approval Screen

- packages/core-mobile/app/errors/swapError.ts
- packages/core-mobile/app/new/features/swap/contexts/SwapContext.tsx
- packages/core-mobile/app/new/features/swap/providers/MarkrProvider.ts
- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/store/posthog/types.ts
To improve swap success rates, if the automatically selected quote fails, we’ll fall back to the second-best quote from the available options.
> Use alternative quotes if auto quote fails

- packages/core-mobile/app/new/features/browser/components/BrowserTab.tsx
**Ticket: [CP-11693]** 
- catch invalid json exception to prevent browser tab crash
https://github.com/user-attachments/assets/2cab154c-81cf-44e0-9b7d-0b23bf87f179
[CP-11693]: https://ava-labs.atlassian.net/browse/CP-11693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11693: wrap JSON.parse with try/catch

- .github/pull_request_template.md
> new template updates

- packages/core-mobile/app/new/features/meld/hooks/useGetTradeLimits.ts
- packages/core-mobile/app/new/features/meld/hooks/useSearchCryptoCurrencies.ts
- yarn.lock
**Ticket: [CP-]**
https://github.com/user-attachments/assets/ff4ade0d-1110-42aa-839f-d24da8d08093
**QA Testing (if applicable)**
- Provide instructions for QA to test this feature thoroughly
- State expected behavior / acceptance criteria
> fix missing meld cryptoCurrencies

- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
**QA Testing (if applicable)**
- Provide instructions for QA to test this feature thoroughly
- State expected behavior / acceptance criteria
> fix ScrollScreen renderFooter display

- packages/core-mobile/android/app/build.gradle
**Ticket: [CP-]**
https://github.com/user-attachments/assets/1b04a9a3-52e2-4dff-bb30-3e3d15b4fdc0
**QA Testing (if applicable)**
- Provide instructions for QA to test this feature thoroughly
- State expected behavior / acceptance criteria
> flipped enable flag secure to false to allow for screenshots on android

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
**Ticket: [CP-11519](https://ava-labs.atlassian.net/browse/CP-11519)**
https://github.com/user-attachments/assets/5711a41a-f1d6-4510-a32a-c0a4715fada8
**QA Testing (if applicable)**
- Provide instructions for QA to test this feature thoroughly
- State expected behavior / acceptance criteria
Please check all that apply (if …
> prevent balance polling from causing flashing on empty wallet state
