ava-labs/core-mobile

- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- packages/core-mobile/scripts/bitrise/detox/iosInternalRegressionRunner.sh
- Breaking changes were merged for the iosInternalE2e.sh runner.  Changed to ci detox configuration.
> QA - Fix ipa path

- packages/core-mobile/scripts/bitrise/triggerIosInternalBuild.sh
triggerIosInternalBuild.sh didn't parse the variables correctly. thus, the iOS workflow never got triggered
> Fix iOS workflow not getting triggered on Bitrise

- .github/dependabot.yml
- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/jest.config.js
- packages/core-mobile/package.json
- yarn.lock
* updated react-native-sentry to 5.31.1
* ignored react-native-mmkv because we're using the latest version(2.12.2) which is compatible with our project. The version 3.x.x requires higher version of react-native with turbo-module turned on.
> CP-9109: Update dependencies - Phase 9

- packages/core-mobile/app/store/rpc/handlers/wc_sessionRequest/namespaces.ts
- packages/core-mobile/app/store/rpc/handlers/wc_sessionRequest/wc_sessionRequest.test.ts
- packages/core-mobile/app/store/rpc/handlers/wc_sessionRequest/wc_sessionRequest.ts
- it seems adding only mainnet or testnet chainIds depend on the current developer mode for avax and btc in wc namespace will throw error `invalid chainId...` error.  we should instead include all of them in the initial session proposal.
> Add mainnet and testnet chainids

- packages/core-mobile/app/contexts/SendNFTContext.tsx
- packages/core-mobile/app/contexts/SendTokenContext.tsx
**Ticket: [CP-9171]** 
* In the [previous PR](https://github.com/ava-labs/core-mobile/pull/1566) aimed at speeding up BTC send, the state validation logic was moved, and the `canSubmit: true` setting was left out of the sendState. Since we already manage the `canSubmit` state within the hook, we can pass it directly to the sendState.
[CP-9171]: https://ava-labs.atlassian.net/browse/CP-9171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9171: Fix bug causing NFT send failure

- packages/core-mobile/app/store/rpc/handlers/account/avalanche_renameAccount/avalanche_renameAccount.test.ts
- packages/core-mobile/app/store/rpc/handlers/account/avalanche_renameAccount/avalanche_renameAccount.ts
- packages/core-mobile/app/store/rpc/handlers/account/avalanche_renameAccount/utils.ts
- packages/core-mobile/app/store/rpc/handlers/index.ts
- packages/core-mobile/app/store/rpc/handlers/wc_sessionRequest/wc_sessionRequest.test.ts
- packages/core-mobile/app/store/rpc/providers/walletConnect/walletConnect.ts
- packages/core-mobile/app/store/rpc/types.ts
**Ticket: [CP-8964]** 
* Add `avalanche_renameAccount` rpc method
* Related PR: https://github.com/ava-labs/extension-avalanche-playground/pull/50
https://github.com/user-attachments/assets/2437c092-4a06-467e-b7dc-cd71478e4168
* Use playground to rename the account (see PR link above)
[CP-8964]: https://ava-labs.atlassian.net/browse/CP-8964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-8964: add avalanche_renameAccount rpc method

- packages/core-mobile/app/store/balance/slice.ts
**Ticket: [CP-9194]** 
- set data is inaccurate when tokens are not yet in redux.
https://github.com/user-attachments/assets/7af60369-b35d-448d-b67c-243455a7f1df
[CP-9194]: https://ava-labs.atlassian.net/browse/CP-9194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9194: Fix 0 balance on fresh install

- packages/core-mobile/android/app/src/main/java/com/avaxwallet/CoreOkHttpClientFactory.kt
- packages/core-mobile/android/app/src/main/java/com/avaxwallet/MainApplication.kt
- packages/core-mobile/android/app/src/main/java/com/avaxwallet/UserAgentInterceptor.kt
this is another attempt to avoid getting rate limited by cloudflare. looks like people have reported this kind of issue before https://community.cloudflare.com/t/bot-traffic-control/320928/2. basically the default user agent that our app uses is usually just `okhttp/x.x.x` and cloudflare may consider that a bot. this pr manually sets the user agent for all requests to a standard format as specified here https://www.scientiamobile.com/correctly-form-user-agents-for-mobile-apps/
for example: 
default user agent:  **okhttp/4.11.0**
new user agent:
**avaxwallet/0.0.0.1 Mozilla/5.0 (Linux; Android 13; Pixel 7 Build/TQ1A.221205.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.127 Mobile Safari/537.36**
> Use custom user agent on Android

- .github/dependabot.yml
- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- packages/core-mobile/patches/react-native-aes-crypto+1.3.10.patch
- yarn.lock
* revert `react-native-aes-crypto`
* ignore `react-native-aes-crypto` from dependabot since the latest version crashes on android
> Revert react-native-aes-crypto

- packages/core-mobile/index.js
* Hide splash screen immediately for storyboook app launching
> fix: Hide splash screen immediately after storyboook app launching

- packages/core-mobile/ios/AvaxWallet.xcodeproj/project.pbxproj
- packages/core-mobile/ios/NotificationServiceExtension/Info.plist
- packages/core-mobile/ios/NotificationServiceExtensionInternal/Info.plist
it seems like the bundle version couldn't get overridden when the plist auto generate option is enabled. this pr disables it and also adds bundle id into the plist files
> Fix iOS CI #2

- packages/core-mobile/patches/react-native-graph+1.1.0.patch
**Ticket: [CP-9277]** 
We were accessing the data even when it is undefined (since we need to fetch new data when selecting a new timeframe). The fix is just to patch react native graph to check for undefined data.
[CP-9277]: https://ava-labs.atlassian.net/browse/CP-9277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9277: Fix watchlist crash when selecting a new timeframe

- .github/dependabot.yml
- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-9279]** 
* `react-native-keychain` version 8.2.0 is slowing down the Android app’s launch time, as mentioned in this [open issue](https://github.com/oblador/react-native-keychain/issues/630). Let’s revert to the previous version we were using.
[CP-9279]: https://ava-labs.atlassian.net/browse/CP-9279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9279: revert react-native-keychain version to 8.1.1

- packages/core-mobile/app/services/fcm/AppCheckService.ts
- packages/core-mobile/app/services/notifications/balanceChange/registerDeviceToNotificationSender.ts
- packages/core-mobile/app/services/notifications/balanceChange/subscribeForBalanceChange.ts
- packages/core-mobile/app/store/notifications/listeners/listeners.ts
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.test.ts
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.ts
- packages/core-mobile/app/utils/httpClient.ts
this pr makes the balance change notifications code a bit more efficient by:
- not calling subscribe/unsubscribe logic unless the feature flag has been updated
- not calling subscribe logic if user has not been prompted for balance change notifications before
> AppCheck clean up

- packages/core-mobile/app/screens/drawer/notifications/Notifications.tsx
- packages/core-mobile/app/store/notifications/listeners/handleMaybePromptBalanceNotification.test.ts
- packages/core-mobile/app/store/notifications/listeners/handleMaybePromptBalanceNotification.ts
- packages/core-mobile/app/store/notifications/listeners/listeners.ts
This PR uses `selectIsBalanceChangeNotificationsBlocked` to block notification feature if disabled.
- should not see notification switch in Notifications settings
- should stop receiving notifications
- should not see "enable notifications" prompt on wallet first open
- [] I have verified the code works
> Fix ff balance notificaitons

- packages/core-mobile/scripts/bitrise/detox/androidInternalE2ENoReuseAppState.sh
- Pixel6 is only for parameterized tests on regression. I found out pixel6 not correctly handled on smoke run. It should bypass the parameterized tests on smoke run correctly 
> QA - Handle pixel6 correctly for bitrise smoke run 

- .yarnrc.yml
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-9266]** 
- always prompt permission dialog when a website is requesting camera and file download permission
- custom permission prompt is displayed before the system permission prompt
https://github.com/ava-labs/react-native-webview/tree/cp-9266
camera permission request
https://github.com/user-attachments/assets/87c0635e-cb36-4aec-9521-9af0b64b0fab
file download permission request
https://github.com/user-attachments/assets/066a0b50-e01c-48a4-90d2-f5d36fa946e4
[CP-9266]: https://ava-labs.atlassian.net/browse/CP-9266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9266: use forked react-native-webview package

- packages/core-mobile/app/screens/drawer/notifications/Notifications.tsx
- packages/core-mobile/e2e/config.json
- packages/core-mobile/e2e/configs/regressionConfig.json
- packages/core-mobile/e2e/configs/reuseStateConfig.json
- packages/core-mobile/e2e/helpers/loginRecoverWallet.ts
- packages/core-mobile/e2e/helpers/warmup.ts
- packages/core-mobile/e2e/locators/burgerMenu/bugerMenu.loc.ts
- packages/core-mobile/e2e/locators/commonEls.loc.ts
- packages/core-mobile/e2e/pages/burgerMenu/burgerMenu.page.ts
- packages/core-mobile/e2e/pages/burgerMenu/notifications.page.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- packages/core-mobile/e2e/tests/notification/sendNotification.e2e.ts
- packages/core-mobile/e2e/tests/settings/notification.e2e.smoke.ts
- New: notification setting switch toggling testing 
- getting ready for testing notification send/receive after the transaction activity. Currently I marked the test to be ignored because the notification is currently broken - https://ava-labs.atlassian.net/browse/CP-9295
- Please note that `verifyPushNotification`, `tapPushNotification`, and `verifyNoPushNotification` are added as placeholders for future testing. We can update the methods and remove the ignore test label once the push notification is fixed
> QA - New: Notification setting tests and getting ready for notification service testing

- packages/core-mobile/app/navigation/wallet/NFTSendStack.tsx
- packages/core-mobile/app/screens/nft/send/NftSend.tsx
**Ticket: [CP-7922](https://ava-labs.atlassian.net/browse/CP-7922)** 
- Please let me know if there is a better way to do this.  It's been awhile since i've worked on a developer ticket.
- Added the QR scanner to the address field on the Send Nft screen.  
- As a user I don't want to have to type out someones address manually each time to send an nft
https://github.com/user-attachments/assets/da08ed95-8c3f-47f4-9f0f-ce24cf56edb2
[CP-7922]: https://ava-labs.atlassian.net/browse/CP-7922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add camera qr scanner to nftSendStack

- packages/core-mobile/app/navigation/WalletScreenStack/WalletScreenStack.tsx
- packages/core-mobile/app/screens/nft/NftManage.tsx
- packages/core-mobile/app/screens/tokenManagement/TokenManagementItem.tsx
- packages/core-mobile/e2e/locators/collectibles.loc.ts
- packages/core-mobile/e2e/locators/commonEls.loc.ts
- packages/core-mobile/e2e/locators/plusMenu.loc.ts
- packages/core-mobile/e2e/pages/collectibles.page.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- packages/core-mobile/e2e/pages/plusMenu.page.ts
- packages/core-mobile/e2e/pages/portfolio.page.ts
- packages/core-mobile/e2e/tests/network/manageToken.e2e.ts
- packages/core-mobile/e2e/tests/nft/manageNft.e2e.ts
- packages/core-mobile/e2e/tests/plusIcon/plusIcon.e2e.ts
New
1. ManageToken - Go to manage token screen > toggle ON and OFF > Verify the token is visible and NOT visible 
2. ManageNFT - pretty much same idea with manage token but for NFT 
3. PlusIcon option testing - SWAP & BUY are ONLY available on C-chain. Test the plusIcon options by network 
> QA - New: Test manage token & NFT and plusIcon options by networks

- packages/core-mobile/ios/AvaxWallet/Info.plist
- packages/core-mobile/ios/AvaxWallet/InfoRelease.plist
- packages/k2-mobile/ios/K2Mobile/Info.plist
looks like this was added way back in the early days. removing it since Apple is complaining we don't have a valid description string for it.
> remove NSLocationWhenInUseUsageDescription

- packages/core-mobile/app/components/svg/ReloadSVG.tsx
- packages/core-mobile/app/screens/portfolio/account/AccountItem.tsx
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/helpers/assertions.ts
- packages/core-mobile/e2e/locators/accountManage.loc.ts
- packages/core-mobile/e2e/locators/commonEls.loc.ts
- packages/core-mobile/e2e/pages/accountManage.page.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- packages/core-mobile/e2e/pages/portfolio.page.ts
- packages/core-mobile/e2e/tests/portfolioTab/manageAccounts.e2e.ts
- packages/core-mobile/package.json
- yarn.lock
- New: Manage account testing
1. Edit account name with invalid text > Fail
2. Edit account name with valid text > Success 
3. Copy address on manage account section > Success 
- Verified the tests passing on both iOS and Android
> QA - New: Manage accounts

- packages/core-mobile/app/screens/bridge/components/BridgeTransactionItem.tsx
- packages/core-mobile/e2e/locators/activityTab.loc.ts
- packages/core-mobile/e2e/pages/activityTab.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/activityTab/activityTab.e2e.smoke.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrationsCore.e2e.smoke.ts
- Small fixes for Android smoke testing. 
- Verified the changes on both iOS and Android. 
> QA - small fixes for the smoke test

- packages/core-mobile/app/screens/drawer/notifications/Notifications.tsx
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.test.ts
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.ts
**Ticket: [CP-9389]** 
when trying to subscribe to the backend, we will skip the logic if the balance notification prompt has not been presented to user. this means users will never receive any notifications. this happens in 2 cases AFAIK:
case 1:
- balance change notification flag is disabled
- user has latest prod build
- user goes to app settings/notifications 
- the Allow Push Notifications banner is displayed 
- user clicks `Open Device Settings`
- this will toggle all the switches to ON (even for the ones that are not displayed like the `Balance` switch)
- balance change notification flag is enabled
- `Balance` notification switch is displayed with ON value
- user will never receive balance notifications unless he/she toggles the switch to OFF + reopens the app + approves prompt …
> Fix balance notification subscription issue

- packages/core-mobile/app/screens/drawer/notifications/Notifications.tsx
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.test.ts
- packages/core-mobile/app/store/notifications/listeners/subscribeBalanceChangeNotifications.ts
**Ticket: [CP-9389]** 
when trying to subscribe to the backend, we will skip the logic if the balance notification prompt has not been presented to user. this means users will never receive any notifications. this happens in 2 cases AFAIK:
case 1:
- balance change notification flag is disabled
- user has latest prod build
- user goes to app settings/notifications 
- the Allow Push Notifications banner is displayed 
- user clicks `Open Device Settings`
- this will toggle all the switches to ON (even for the ones that are not displayed like the `Balance` switch)
- balance change notification flag is enabled
- `Balance` notification switch is displayed with ON value
- user will never receive balance notifications unless he/she toggles the switch to OFF + reopens the app + approves prompt …
> Fix balance notification subscription issue (#2027)

- packages/core-mobile/app/screens/earn/Confirmation/Confirmation.tsx
- packages/core-mobile/app/screens/earn/components/StakeCard.tsx
- packages/core-mobile/app/screens/earn/durationScreen/DurationScreen.tsx
- packages/core-mobile/app/services/earn/getStakeEndDate.ts
- packages/core-mobile/app/services/wallet/WalletService.test.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
**Ticket: [CP-9383]** 
These are hotfixes for CP-9383 
- fixed display on stake card where it would display "-20 hours" instead of positive time
- fixes "duration too short" error caused by wrongly passed parameter as seconds instead of ms. 
[CP-9383]: https://ava-labs.atlassian.net/browse/CP-9383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9383 Mobile - unable to stake on prod build 

- packages/core-mobile/scripts/bitrise/detox/iosInternalE2e.sh
- packages/core-mobile/scripts/datadog/updateIosDashboard.sh
- fixes memory use monitor query. the query didn't match the alert threshold.
> Qa fix memory monitor query

- packages/core-mobile/app/components/CalendarInput.tsx
- packages/core-mobile/app/utils/debugging/DevDebuggingConfig.ts
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/locators/Stake/stakeScreen.loc.ts
- packages/core-mobile/e2e/locators/commonEls.loc.ts
- packages/core-mobile/e2e/pages/Stake/stake.page.ts
- packages/core-mobile/e2e/pages/commonEls.page.ts
- packages/core-mobile/e2e/tests/stake/stakingTestnet.e2e.ts
- Stake was blocked due to daylight saving time and we had to do a hotfix release, 0.14.18. 
- This should cover the different timelines for staking, `1 day, 1 month, 3 months, 6 months, 1 year, and custom (maximum time)`  cc @neven-s 
- Tested on both iOS and Android
- We're only testing the different duration stakings on testnet
> QA New: Stake duration selections

- bitrise.yml
- packages/core-mobile/scripts/bitrise/detox/androidE2ENoReuseAppState.sh
- packages/core-mobile/scripts/datadog/updateAndroidDashboard.sh
- The android dashboard was being updated on internal test runs and so I created a bitrise workflow that only gets called on android-e2e builds during regression. 
- Small fix for android dashboard update script
> run update script android-e2e workflow

- packages/core-mobile/app/screens/portfolio/account/AccountItem.tsx
- packages/core-mobile/app/screens/portfolio/home/components/Cards/ActiveNetworkCard/ActiveNetworkCard.tsx
- packages/core-mobile/app/screens/portfolio/home/components/Cards/InactiveNetworkCard.tsx
- packages/core-mobile/app/screens/portfolio/home/components/PortfolioHeader.tsx
- packages/core-mobile/app/screens/portfolio/network/components/NetworkTokensHeader.tsx
- packages/core-mobile/app/screens/rpc/components/v2/SessionProposal/AccountItem.tsx
- packages/core-mobile/app/store/balance/slice.ts
**Ticket: [CP-9361]** 
We weren't filtering out blacklisted tokens when counting the total balance. This pr adjusts that.
https://github.com/user-attachments/assets/def8932d-ddd4-4aa3-b58b-8bf4be67a238
Please make sure this works for all EVM networks
[CP-9361]: https://ava-labs.atlassian.net/browse/CP-9361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9361: User can't hide scam tokens with a large non-zero balance

- packages/core-mobile/app/components/PortfolioListItem.tsx
- packages/core-mobile/app/screens/portfolio/home/components/PortfolioHeader.tsx
- packages/core-mobile/app/screens/portfolio/network/components/NetworkTokensHeader.tsx
- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/locators/portfolio.loc.ts
- packages/core-mobile/e2e/pages/manageTokens.page.ts
- packages/core-mobile/e2e/pages/networksManage.page.ts
- packages/core-mobile/e2e/pages/portfolio.page.ts
- packages/core-mobile/e2e/tests/balance/manageTokenBalance.e2e.ts
- packages/core-mobile/e2e/tests/portfolioTab/tokens/manageToken.e2e.ts
- This PR covers the automation testing for the ticket - https://ava-labs.atlassian.net/browse/CP-9361?atlOrigin=eyJpIjoiNThjNzNkYjIxZDYyNGMzMThjZDk5ZWQ3OTVmMDYzMjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ cc @atn4z7 
- Test Scenario: 
- Get full balance before hiding token > Hide token on C-Chain > Verify the differences 
- Same deduction scenario with Ethereum network 
- Get full balance before showing token that we just blocked > Show token on C-Chain > Verify the differences 
- Same add scenario with Ethereum network 
- Tested on both iOS and Android and it's passing fine. 
> QA New Test Balance after hiding and showing token

- packages/core-mobile/app/screens/earn/components/Balance.tsx
- packages/core-mobile/app/screens/portfolio/home/components/Cards/ActiveNetworkCard/PChainAssetList.tsx
- p-chain balance is display in wrong decimal place in active network card
- p-chain staked balance was not showing up in balance dashboard
before
after
- manual
> Fixed incorrect p-chain token display balance

- packages/core-mobile/app/screens/network/NetworkDetails.tsx
- packages/core-mobile/metro.config.js
- yarn.lock
**Ticket: [CP-9376]** 
https://github.com/user-attachments/assets/fa4be047-1b18-421e-996b-627840e329e0
[CP-9376]: https://ava-labs.atlassian.net/browse/CP-9376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9376: Navigate back to Portfolio after connecting network on NetworkDetails screen

- packages/core-mobile/app/services/network/NetworkService.test.ts
- packages/core-mobile/app/services/network/NetworkService.ts
**Ticket: [CP-9470]** 
This fixes issue by avoid failing whole getNetworks call if one of inner calls fail 
- added unit test
[CP-9470]: https://ava-labs.atlassian.net/browse/CP-9470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9470 Networks and assets are not displayed if DeBank api is failing

- packages/core-mobile/app/components/HeaderAccountSelector.tsx
- packages/core-mobile/app/hooks/earn/useStakes.ts
**Ticket: [CP-9503]** 
The bug actually happens on mainnet as well. It happens because the address is updated async after we toggle developer mode. In that brief moment, if we try to open up Stake screen, it will try to fetch stakes for the old address, which will return 0 stakes. This pr fixes it by making sure we fetch stakes with the correct address for the current developer mode. For example, when developer mode is on, we will only allow fetching with address like `P-fuji1k38sj9z9n5vfw5239vv68cns68x579k4rw8yhe`.
https://github.com/user-attachments/assets/8f25ab38-ee35-4bd6-b176-1d096b13513b
Please make sure stakes are being fetching correctly everywhere in the app
[CP-9503]: https://ava-labs.atlassian.net/browse/CP-9503?atlOrigin=eyJpIjoiNWRk …
> CP-9503: Should not display Get Started screen for user with active stakes history on Testnet Stake tab

- packages/core-mobile/app/AppHook.ts
- packages/core-mobile/app/components/UniversalTokenSelector.tsx
- packages/core-mobile/app/screens/earn/Confirmation/Confirmation.tsx
- packages/core-mobile/app/screens/earn/StakeDetails.tsx
- packages/core-mobile/app/screens/earn/components/StakeCard.tsx
- packages/core-mobile/app/screens/watchlist/components/WatchList.tsx
**Ticket: [CP-9507]** 
We were passing strings to the formatter and when the amount is over $1000, it will break the formatter since the string will contain a comma. For example, 1,000.00. This pr makes sure we only pass numbers to the formatter.
Please make sure to test Stake Card, Stake Details, Stake Confirmation and Send
[CP-9507]: https://ava-labs.atlassian.net/browse/CP-9507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9507: Don't show `$NaN USD` on Stake Card  & Send/Swap Form

- packages/core-mobile/app/AppHook.ts
- packages/core-mobile/app/components/NetworkFeeSelector.tsx
- packages/core-mobile/app/screens/portfolio/ownedTokenDetail/OwnedTokenDetail.tsx
- packages/core-mobile/app/screens/rpc/components/v2/SpendLimits.tsx
- packages/core-mobile/app/utils/Utils.ts
- packages/core-mobile/app/utils/string/toNumber.ts
**Ticket: [CP-9507]** 
We were passing strings to the formatter and when the amount is over $1000, it will break the formatter since the string will contain a comma. For example, 1,000.00. This pr makes sure we only pass numbers to the formatter.
Please make sure the amounts are showing correctly on Token Details, Network Fee Selector, Edit Fee and Spend Limit
[CP-9507]: https://ava-labs.atlassian.net/browse/CP-9507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9507: Don't show `$NaN USD` on Token Details, Network Fee Selector, Edit Fee and Spend Limit

- packages/core-mobile/app/seedless/services/SeedlessSessionManager.ts
- packages/core-mobile/app/seedless/store/listeners.ts
**Ticket: [CP-9512]** 
We are not prompting re-auth for certain token refresh errors. I talked to Cubist and they recommended adding another check for `e.operation === 'signerSessionRefresh'`.
Testing with setting `session_lifetime` to 1 minute
**Before**
https://github.com/user-attachments/assets/f5d67a9e-9a82-4012-8b8d-1aaf083a7956
**After**
https://github.com/user-attachments/assets/1c219e20-d2ab-4158-be6d-bd4924869b87
https://github.com/user-attachments/assets/4fbef4a6-1ff9-4887-87ea-6165c5d2dbac
I did try playing around with `refresh_lifetime` but our current code is working fine for that 
Please make sure token refresh is still working and users are only prompted for re-auth when necessary. Please use builds `0.0.0.4125` and `0.0.0.4126` to test (I set the session lifetime to 1 …
> CP-9512: Fix Seedless reauth not working 

- packages/core-mobile/app/seedless/store/listeners.test.ts
- packages/core-mobile/app/seedless/store/listeners.ts
- yarn.lock
make sure we do not ever call re-auth for mnemonic wallet
also add undefined error code check since Cubist also recommended this
https://github.com/user-attachments/assets/e5bf42c7-08e3-4659-a3e5-06040b007c27
> More Seedless Reauth Improvement

- packages/core-mobile/app/screens/bridge/Bridge.tsx
- packages/core-mobile/app/screens/bridge/hooks/useBridge.ts
- packages/core-mobile/app/screens/bridge/hooks/useBridgeNetworkPrice.ts
- packages/core-mobile/app/screens/bridge/hooks/useEstimatedReceiveAmount.ts
- packages/core-mobile/app/screens/bridge/hooks/useGetBridgeFees.ts
- packages/core-mobile/app/screens/bridge/hooks/useMaxTransferAmount.ts
- packages/core-mobile/app/screens/bridge/hooks/usePendingBridgeTransactions.ts
- packages/core-mobile/app/services/bridge/UnifiedBridgeService.ts
- packages/core-mobile/app/utils/data/caip.ts
- packages/core-mobile/app/vmModule/ApprovalController/ApprovalController.ts
- packages/core-mobile/app/vmModule/handlers/btcSignTransaction.ts
**Ticket: [CP-9545]** 
* implement `useMaxTransferAmount` for calculating max amount
* implement `useEstimatedReceiveAmount` to show estimated receive amount, using `estimateReceiveAmount` function in unified bridge
* implement missing `btcSignMessage` handler
[CP-9545]: https://ava-labs.atlassian.net/browse/CP-9545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9545: Fix error with insufficient balance error when hit max with native tokens

- packages/core-mobile/app/contexts/SwapContext/performSwap/performSwap.ts
**Ticket: [CP-9556]** 
We were using string instead of number/bigint for `txBuildData.gas` so we would get something like `0x181883` instead of  `0x2c67b`
Please make sure swapping still works
[CP-9556]: https://ava-labs.atlassian.net/browse/CP-9556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9556: Use correct gas limit for swap

- packages/k2-alpine/src/components/PageControl/PageControl.stories.tsx
- packages/k2-alpine/src/components/PageControl/PageControl.tsx
- packages/k2-alpine/src/components/PinInput/PinInput.stories.tsx
**Ticket: [CP-9492]** 
* implement PageControl and its storybook
https://github.com/user-attachments/assets/00d06bc0-97d8-4e3a-95a8-ec7db4d078e3
[CP-9492]: https://ava-labs.atlassian.net/browse/CP-9492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9492: PageControl component

- packages/core-mobile/app/hooks/earn/useClaimFees.ts
- packages/core-mobile/app/hooks/earn/useClaimRewards.ts
- packages/core-mobile/app/hooks/earn/utils/extractNeededAmount.test.ts
- packages/core-mobile/app/hooks/earn/utils/extractNeededAmount.ts
- packages/core-mobile/app/screens/earn/ClaimRewards.tsx
- packages/core-mobile/app/screens/send/utils/types.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
- packages/core-mobile/app/services/wallet/utils.ts
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-9562]** 
Issue 1: we were rounding up fee calculation which results in a case where actual balance - fee (rounded up) doesn't equal to actual balance - fee (raw). @neven-s adjusted the round up logic in token unit in the utils sdk to make it round down instead. it seems to be working. 
Issue 2: when calculating the estimated export P fee, we were using a fake amount that is less than available balance to try to estimate the fee. however, this is not reliable and usually much smaller than the actual required fee. instead of doing that, I have adjusted it so that we would try with the actual available amount. if it errors out with the insufficient funds message, we will grab the `missing amount` from the message and deduct it from the available amount. this will guarantee we …
> CP-9562: Fix unable to claim rewards on testnet

- packages/core-mobile/app/components/EditFees.tsx
- packages/core-mobile/app/components/NetworkFeeSelector.tsx
- packages/core-mobile/app/screens/rpc/components/shared/RpcRequestBottomSheet.tsx
- packages/core-mobile/app/screens/rpc/components/v2/AlertScreen.tsx
- packages/core-mobile/e2e/locators/Stake/stakeScreen.loc.ts
- packages/core-mobile/e2e/locators/popupModal.loc.ts
- packages/core-mobile/e2e/pages/Stake/stake.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/plusIcon/bridge/bridge.e2e.ts
- Select a random dynamic fee selector during staking on testnet
- Handle the new approve transaction for Bitcoin > AVAX Bridge 
> QA - Select dynamic fee during stake on testnet

- packages/core-mobile/app/hooks/earn/useClaimFees.ts
- packages/core-mobile/app/hooks/earn/useEstimateStakingFees.ts
- packages/core-mobile/app/hooks/earn/useIssueDelegation.ts
- packages/core-mobile/app/screens/earn/components/Balance.tsx
- packages/core-mobile/app/services/earn/EarnService.ts
- packages/core-mobile/app/services/earn/exportC.test.ts
- packages/core-mobile/app/services/earn/exportC.ts
- packages/core-mobile/app/services/earn/types.ts
- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
- packages/core-mobile/app/services/wallet/types.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/store/posthog/types.ts
**Ticket: [CP-9586]** 
This pr follows the same solution in https://github.com/ava-labs/core-mobile/pull/2127. We can't rely on our simulated utxos to calculate correct fees. The fees will always be smaller than the actual needed fees. Hence, we will just grab whatever missing amount from the error message when submitting the delegation and deduct that from the total staking amount and retry. 
To prevent the case where the missing amount is super large, I added `p-fee-adjustment-threshold` feature flag, which is set to 0.1% currently. When the missing amount goes over 0.1%, we will reject the transaction. From my testing, the ratio seems to be less than 0.005%. 
`p-fee-adjustment-threshold`
```This flag defines the maximum allowable ratio of the additional fee adjustment (missingAmount) …
```
> CP-9586: Fix not able to stake on mainnet and testnet

- packages/core-mobile/e2e/helpers/actions.ts
- packages/core-mobile/e2e/pages/Stake/stake.page.ts
- packages/core-mobile/e2e/pages/popUpModal.page.ts
- packages/core-mobile/e2e/tests/plusIcon/walletConnect/dappIntegrationsRPCPlayground.e2e.ts
- packages/core-mobile/e2e/tests/portfolioTab/subTabs.e2e.ts
- packages/core-mobile/e2e/tests/stake/stakingTestnet.e2e.ts
- We tested all the possible duration stake testing, but it failed due to the existing bug and always became flaky. On this PR, I randomly chose one duration, and we'll only test one stake on testnet. It could fail again if it chooses a different fee other than `normal`, but it will be addressed soon.
- This PR also contains other small flakiness around the testing suite
> QA fix staking and rpc call testing

- .github/dependabot.yml
- packages/core-mobile/ios/Podfile.lock
- packages/core-mobile/package.json
- packages/core-mobile/patches/@walletconnect+react-native-compat+2.11.0.patch
- packages/core-mobile/polyfills/index.js
- yarn.lock
**Ticket: [CP-9613]** 
- app is crashed on real device, adding back `@walletConnect/react-native-compat` fixed it.
[CP-9613]: https://ava-labs.atlassian.net/browse/CP-9613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9613: Add back @walletConnect/react-native-compat

- bitrise.yml
- We want to be able to run workflows outside of pipelines on bitrise.  This change makes the `share-pipeline-variables` step skippable and the build is successful.
> QA - skip share pipeline vars

- packages/core-mobile/app/screens/earn/ClaimRewards.tsx
- packages/core-mobile/app/screens/earn/components/StakeCard.tsx
**Ticket: [CP-9517]** 
* Use the tokenInCurrencyFormatter function to correctly display the claimable amount and fee.
* Fixed a bug where the currency symbol was duplicated when using currencies other than USD. 
|| Before | After |
| --- | --- | --- |
| Stakes(USD) | <img src=https://github.com/user-attachments/assets/4e4b24aa-1b44-4ce5-9608-78b35113b1fd width=320 /> | <img src=https://github.com/user-attachments/assets/6dadbdb1-a29b-4486-973a-bf1007543407 width=320 /> |
| Stakes(CLP) | <img src=https://github.com/user-attachments/assets/31d0de11-5c10-42f3-91a7-cef4171b1e6c width=320 /> | <img src=https://github.com/user-attachments/assets/b7716c63-2bfc-457c-be1c-827d67299e40 width=320 /> |
| Claim Rewards(USD) | <img src=https://github.com/user-attachments/assets/4de26a11-6c4e-4575-a64e-b …
> CP-9517: Use tokenInCurrencyFormatter to show rewards and fees for staking

- packages/core-mobile/app/components/Avatar.tsx
- packages/core-mobile/app/screens/watchlist/TokenDetails/TokenDetail.tsx
- packages/core-mobile/app/screens/watchlist/components/WatchListItem.tsx
**Ticket: [CP-9622]** 
* Set the default background color of the token logo to white.
| | before | after |
| --- | --- | --- |
| Watchlist | <img src=https://github.com/user-attachments/assets/0fc56754-f793-4bdc-b27f-b25ef8c4f713 width=320 /> | <img src=https://github.com/user-attachments/assets/41a6f9d3-fbc4-4332-8ad1-20a815d87d02 width=320 /> |
| XLM | <img src=https://github.com/user-attachments/assets/6e0bd158-2d84-4c21-b27b-46173b67b5b2 width=320 /> | <img src=https://github.com/user-attachments/assets/d1d9b18c-2d74-4b0d-a0fe-7f0a8913d42f width=320 /> |
|| <img src=https://github.com/user-attachments/assets/5d9fcfd6-04da-43ac-8ae6-6c109aa3f72d width=320 /> | <img src=https://github.com/user-attachments/assets/53e55a7d-d6e1-46ff-a22c-182803a2641d width=320 /> |
[CP-9622]: …
> CP-9622: Set the default background color of the token logo to white.

- packages/core-mobile/app/screens/earn/StakeDetails.tsx
**Ticket: [CP-9517]** 
* Fix showing duplicated currency symbol in StakeDetails
[CP-9517]: https://ava-labs.atlassian.net/browse/CP-9517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9517: Fix showing duplicated currency symbol in StakeDetails

- packages/core-mobile/app/components/InputText.tsx
- packages/core-mobile/app/screens/browser/Browser.tsx
- packages/core-mobile/app/screens/browser/HistoryScreen.tsx
- packages/core-mobile/app/screens/browser/components/EmptyTab.tsx
**Ticket: [CP-9634]** 
* Updated the keyboard type for the browser’s search text input to make entering URLs easier.
[CP-9634]: https://ava-labs.atlassian.net/browse/CP-9634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9634: Fix the keyboard type for the browser’s search text input.

- packages/core-mobile/app/screens/portfolio/account/AccountItem.tsx
- packages/core-mobile/app/screens/portfolio/account/AccountView.tsx
- packages/core-mobile/e2e/pages/accountManage.page.ts
- packages/core-mobile/e2e/tests/portfolioTab/tokens/addCustomToken.e2e.smoke.ts
- Handle flakiness around adding a new account
> QA - smoke test fixes

- packages/core-mobile/app/hooks/browser/useInjectedJavascript.ts
**Ticket: [CP-9375]** 
This is **best effort** to not show `Use Wallet Connect` dialog which pops up randomly in some cases.
The fix is that we track if user have interacted with dApp and only then allow detection of underlying ethereum callbacks upon which we conclude that dApp tried to connect with non-core wallet.
However, there still can be cases when dialog pops up since this is not documented feature.
https://github.com/user-attachments/assets/d24509c8-12e1-42a8-adf2-8110832e2906
- go to Browser tab
- select Pangolin from suggested list
- observe it doesn't pop up Use Wallet Connect dialog until you try to connect wallet
[CP-9375]: https://ava-labs.atlassian.net/browse/CP-9375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> CP-9375 Don't show Use Wallet Connect dialog if not interacted with app

- packages/core-mobile/app/components/NotFoundError.tsx
- packages/core-mobile/app/components/TopLevelErrorFallback.tsx
- packages/core-mobile/app/contexts/DeeplinkContext/DeeplinkContext.tsx
- packages/core-mobile/app/contexts/DeeplinkContext/types.ts
- packages/core-mobile/app/contexts/DeeplinkContext/utils/handleDeeplink.test.ts
- packages/core-mobile/app/contexts/DeeplinkContext/utils/handleDeeplink.ts
- packages/core-mobile/app/navigation/utils.ts
- packages/core-mobile/app/screens/watchlist/TokenDetails/TokenDetail.tsx
- packages/core-mobile/app/screens/watchlist/useTokenDetail.ts
- packages/core-mobile/app/services/earn/utils.test.ts
- packages/core-mobile/app/services/earn/utils.ts
- packages/core-mobile/app/services/fcm/FCMService.ts
- packages/core-mobile/app/services/fcm/types.ts
we can now handle these links:
- `core://watchlist/avalanche-2`: will direct to AVAX watchlist token screen (avalanche-2 is a coingecko id)
- `core://watchlist`: will direct to watchlist tab
- any https link: will open with the in-app browser
**core://watchlist/avalanche-2** 
https://github.com/user-attachments/assets/ff638e6c-51b3-4cab-accb-885a488ddd02
**core://watchlist/somethingnotvalid**
this also applies to any tokens that our backend doesn't index/cache
https://github.com/user-attachments/assets/04231ad0-797b-4607-bdd3-e6abd9c2a943
**https link**
https://github.com/user-attachments/assets/3570f8de-201e-4b63-b8d4-9346907b7d95
In DeeplinkContext.tsx file, you can manually call this to test this new behavior
```
useEffect(() => {
setPendingDeepLink({
url: …
```
> Handle Watchlist Deeplinks

- packages/core-mobile/app/contexts/DeeplinkContext/DeeplinkContext.tsx
- packages/core-mobile/app/services/fcm/FCMService.ts
- packages/core-mobile/app/services/notifications/NotificationsService.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/utils/AudioFeedback.ts
**Ticket: [CP-9664]** 
- News events to channel id mapping was missing, so the android news notification was not delivered.
- use default sound for new notifications
- android notification
https://github.com/user-attachments/assets/7b248d86-03ad-44eb-bd71-18440ade63e2
- default sound for ios notification
https://github.com/user-attachments/assets/5f1c0276-3d2f-4d64-af9b-50f47856aa0a
[CP-9664]: https://ava-labs.atlassian.net/browse/CP-9664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9664: Add missing news events to channel Id mapping

- packages/core-mobile/app/services/notifications/NotificationsService.ts
- notifee.getInitialNotification does not triggerred callback to handle notification data as expected.  switch to use firebaseMessaging.getInitialNotification instead.
> fix iOS background deeplink issue

- packages/core-mobile/app/hooks/useInAppBrowser.ts
- packages/core-mobile/app/services/fcm/FCMService.ts
- packages/core-mobile/app/services/fcm/types.ts
- packages/core-mobile/app/services/notifications/channels.ts
- packages/core-mobile/app/utils/openInAppBrowser.ts
- packages/core-mobile/ios/.xcode.env
- added missing channel sound for new notification on android.
- use `onNotificationOpenedApp` to handle ios background message
- news notification deeplink to watchlist
https://github.com/user-attachments/assets/5a915e03-2a30-4064-b488-cc7a6e19f2c5
- new notification deeplink to in-app-browser
https://github.com/user-attachments/assets/10a8ddbb-3e8f-494f-8adf-d31bd1a68726
- balance change notification keeps user on home page (portfolio tab)
https://github.com/user-attachments/assets/292bdb92-a6c6-49d4-9bc3-d9141e58c55c
> Fix ios background handler

- packages/core-mobile/app/services/fcm/FCMService.ts
- packages/core-mobile/app/services/fcm/types.ts
- packages/core-mobile/ios/.xcode.env
- remove android configuration options for background deeplink to in-app browser, since it only applies to iOS.
- revert change in xcode.env
- add comment to notification data schema for url.
> Notification cleanup

- packages/core-mobile/android/app/src/main/AndroidManifest.xml
- packages/core-mobile/app/hooks/useInAppBrowser.ts
**Ticket: [CP-9632]** 
This PR fixes named titled issue by:
- passing option `showInRecents` when starting in-app browser which enables switching back to it from "app switcher" (recent app list)
- changing launch mode for Android activity to `singleTop` which keeps in-app browser on top of the task when launching app from homescreen
- please follow steps from ticket and observe normal operation
[CP-9632]: https://ava-labs.atlassian.net/browse/CP-9632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9632 Buy flow starts over if app is put in background or inactive while native in-app browser is open on Android

- packages/core-mobile/app/services/passkey/PasskeyService.ts
- update getCredential to use get() instead of getSecurityKey() to avoid iOS prompt only for security key.
- tested on both android and iOS with getCrentials(), and they are both working.
> use get over getSecurityKey to authenticate passkey

- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/store/notifications/listeners/handlePromptNotifications.test.ts
- packages/core-mobile/app/store/notifications/listeners/handlePromptNotifications.ts
- packages/core-mobile/app/store/posthog/slice.ts
**Ticket: [CP-9743]** 
- if user has disabled system notifications, always prompt them to take them to system settings to enable it.
- ff enable-notification-prompt can be turned off to skip prompting user if it becomes an issue.
https://github.com/user-attachments/assets/030f7e74-b4ce-493e-9f59-b7cf8b3ccdbc
[CP-9743]: https://ava-labs.atlassian.net/browse/CP-9743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9743: prompt user to enable notification if disabled in settings

- packages/core-mobile/app/contexts/SwapContext/SwapContext.tsx
- packages/core-mobile/app/hooks/useDebounce.ts
- packages/core-mobile/app/screens/swap/SwapView.tsx
- packages/core-mobile/app/services/swap/SwapService.ts
- packages/core-mobile/app/swap/getSwapRate.ts
**Ticket: [CP-9832]** 
Fetching rates via paraswap can take a bit of time and we were fetching on every keystroke. This pr adds some debounce as well as logic to cancel existing requests.
https://github.com/user-attachments/assets/8a4989ee-5529-4ee4-8583-fe636097f88f
Please make sure swapping is still working normally
[CP-9832]: https://ava-labs.atlassian.net/browse/CP-9832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9832: Update the swap amount correctly with debounce

- packages/core-mobile/app/screens/bridge/hooks/useAssetBalances.ts
- packages/core-mobile/app/screens/portfolio/useSearchableTokenList.ts
- packages/core-mobile/app/screens/send/TokenSelector.tsx
- packages/core-mobile/app/screens/tokenManagement/TokenManagement.tsx
- packages/core-mobile/app/screens/tokenManagement/TokenManagementItem.tsx
- packages/core-mobile/app/store/balance/slice.ts
- packages/core-mobile/app/store/balance/utils.tests.ts
- packages/core-mobile/app/store/balance/utils.ts
- packages/core-mobile/app/store/migrations.ts
- packages/core-mobile/app/store/portfolio/slice.ts
**Ticket: [CP-9868]** 
- TokenSelector and BridgeTokenSelector should obey TokenVisibility rule
https://github.com/user-attachments/assets/f45e7521-78fc-4ca6-9a83-90f7d3da48c5
[CP-9868]: https://ava-labs.atlassian.net/browse/CP-9868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9868: hiden blacklisted tokens in tokenSelector

- packages/core-mobile/app/new/features/onboarding/components/EnterRecoveryPhrase.tsx
- packages/core-mobile/app/new/routes/_layout.tsx
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
**Ticket: [CP-9606]** 
* Implement fade-in/out animation for `Forgot PIN` button
* add `Enter test HD wallet` for testing convenience
https://github.com/user-attachments/assets/62e1c924-d3e0-4f63-85b1-1b0e34002c49
[CP-9606]: https://ava-labs.atlassian.net/browse/CP-9606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9606: Forgot PIN Flow

- packages/core-mobile/app/hooks/earn/useClaimFees.ts
- packages/core-mobile/app/hooks/earn/useClaimRewards.ts
- packages/core-mobile/app/hooks/earn/useDelegation.ts
- packages/core-mobile/app/hooks/earn/useImportAnyStuckFunds.ts
- packages/core-mobile/app/screens/earn/ClaimRewards.tsx
- packages/core-mobile/app/services/earn/EarnService.ts
- packages/core-mobile/app/services/earn/computeDelegationSteps/computeDelegationSteps.test.ts
- packages/core-mobile/app/services/earn/computeDelegationSteps/computeDelegationSteps.ts
- packages/core-mobile/app/services/earn/computeDelegationSteps/utils.ts
- packages/core-mobile/app/services/earn/exportC.test.ts
- packages/core-mobile/app/services/earn/exportC.ts
- packages/core-mobile/app/services/earn/importC.test.ts
- packages/core-mobile/app/services/earn/importC.ts
- packages/core-mobile/app/services/earn/utils.ts
- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/services/wallet/WalletService.test.ts
- packages/core-mobile/app/services/wallet/WalletService.tsx
- packages/core-mobile/app/services/wallet/utils.test.ts
- packages/core-mobile/app/services/wallet/utils.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/store/posthog/types.ts
**Ticket: [CP-9864]** 
This pr fixes a couple of things:
- import C and export C "tx failed due to insufficient funds" issue (https://ava-labs.atlassian.net/browse/CP-9864) :
- this affects delegation as well as claiming rewards
- the error message actually just means the supplied base fee is too low. the fix is just to increase base C-Chain fee by 100%. web did the same [here](https://github.com/ava-labs/core-web/pull/73) 
- I also go ahead and make this c-chain base fee multiplier dynamic via the posthog flag`c-base-fee-multiplier`
- unable to claim issue (https://ava-labs.atlassian.net/browse/CP-9833)
- this is due to us using the wrong amount for export P. the fix is in this [commit](https://github.com/ava-labs/core-mobile/pull/2223/commits/fe20e8839a20980aba42bb6d4fabee89b140eab9).
- …
> CP-9864: Fix "export tx failed due to insufficient funds" error message when staking 

- packages/core-mobile/app/hooks/earn/useDelegation.ts
- packages/core-mobile/app/screens/earn/Confirmation/Confirmation.tsx
- packages/core-mobile/app/services/earn/computeDelegationSteps/computeDelegationSteps.test.ts
- packages/core-mobile/app/services/earn/computeDelegationSteps/computeDelegationSteps.ts
- packages/core-mobile/app/services/earn/computeDelegationSteps/utils.ts
- packages/core-mobile/app/services/posthog/types.ts
- packages/core-mobile/app/store/posthog/slice.ts
- packages/core-mobile/app/store/posthog/types.ts
**Ticket: [CP-9880]** 
Looks like we will occasionally run into situations where we are missing 10000-100000 nAVAX (0.0001 AVAX) when trying to do a delegation that involves a cross chain transfer from C-Chain. This pr adds a buffer (currently configured at 400% via the `cross-chain-fees-multiplier` feature flag) to all the fees, which are then added to the final amount to transfer. This seems to work okay since the actual fees are usually way lesser. The only drawback is users will have a little bit AVAX remaining on P-Chain after submitting the delegation.  
https://github.com/user-attachments/assets/8146bed0-1fa3-4a8b-93f7-df91e3e780e0
Please re-test all the different staking scenarios
[CP-9880]: …
> CP-9880: add a buffer to all fees for cross chain amount

- packages/core-mobile/app/App.tsx
- packages/core-mobile/app/navigation/NavUtils.tsx
**Ticket: [CP-9750]** 
- disable KeyboardAvoidingView when we are in the browser tab to prevent webview's content from being pushed up
- also hide bottom tab bar globally whenever keyboard appears
https://github.com/user-attachments/assets/5bd6e0d2-e1bc-4a9d-8d8d-7f824420a73b
Please retest all dapp interaction within the browser
[CP-9750]: https://ava-labs.atlassian.net/browse/CP-9750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9750: Fix in-app browser cutting off token search bar in LFJ

- packages/core-mobile/ios/AppDelegate.mm
**Ticket: [CP-9742]** 
- use ApplicationDidbecomeActive to reset badgeCount in userDefaults to 0 whenever app is active
https://github.com/user-attachments/assets/622660bd-5f01-4297-8455-f8dedace9738
[CP-9742]: https://ava-labs.atlassian.net/browse/CP-9742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9742: Reset userDefault badgeCount when app becomes active

- packages/core-mobile/e2e/tests/plusIcon/bridge/bridge.e2e.ts
- packages/core-mobile/e2e/tests/transactions/bitcoin/bridgeBitcoin.e2e.ts
- packages/core-mobile/e2e/tests/transactions/bitcoin/sendBitcoin.e2e.ts
- packages/core-mobile/e2e/tests/transactions/cchain/bridge/bridge.e2e.ts
- packages/core-mobile/e2e/tests/transactions/cchain/send/send.e2e.smoke.ts
- packages/core-mobile/e2e/tests/transactions/cchain/send/sendERC20.e2e.parameterized.ts
- packages/core-mobile/e2e/tests/transactions/cchain/send/sendNft.e2e.ts
- packages/core-mobile/e2e/tests/transactions/cchain/stake/stakingMainnet.e2e.ts
- packages/core-mobile/e2e/tests/transactions/cchain/stake/stakingTestnet.e2e.ts
- packages/core-mobile/e2e/tests/transactions/cchain/swap/swap.e2e.parameterized.ts
- packages/core-mobile/e2e/tests/transactions/cchain/swap/swap.e2e.smoke.ts
- packages/core-mobile/e2e/tests/transactions/cchain/swap/swapDapps.e2e.ts
- packages/core-mobile/e2e/tests/transactions/ethereum/bridgeEthereum.e2e.ts
- packages/core-mobile/e2e/tests/transactions/ethereum/sendEth.e2e.ts
- packages/core-mobile/e2e/tests/transactions/ethereum/sendEthNft.e2e.ts
- packages/core-mobile/e2e/tests/transactions/pchain/sendPchain.e2e.ts
- packages/core-mobile/e2e/tests/transactions/xchain/sendXchain.e2e.ts
The detox tests are restructured to run for transactions tests only. Sometimes we're requested to run tests only for transactions. I've collected and refine all the transaction related tests into `transactions` directory and it has all networks, C/P/X/Ethereum/Bitcoin. 
We can now just run tests with the command `detox .... e2e/tests/transactions` 
> QA Chore - transactions structured automation tests

- packages/core-mobile/app/services/swap/SwapService.ts
from @meeh0w 
```
my guess is something must've changed on Paraswap side, because previously when we would fetch swap rates for AVAX, we could pass srcToken=AVAX as parameter, now we need to change it to srcToken=0xeee(...) (all Es).
I'm basing my guess solely off of the fact that it's also broken for Mobile atm. and as far as I can tell, this portion of code was changed ~10months ago for mobile.
```
same fix as https://github.com/ava-labs/core-extension/pull/149
**before**
https://github.com/user-attachments/assets/d013466e-b836-465e-9c1c-c8fa454fd85a
**after**
https://github.com/user-attachments/assets/b4a2dd64-6f39-4b56-b918-6b2a1e0f999c
Please test swapping AVAX/wAVAX
> fix swapping AVAX/wAVAX

- packages/core-mobile/app/new/common/hooks/useFormatCurrency.ts
- packages/core-mobile/app/new/features/track/components/ChartOverlay.tsx
- packages/core-mobile/app/new/features/track/components/SelectedChartDataIndicator.tsx
- packages/core-mobile/app/new/features/track/components/SelectionDot.tsx
- packages/core-mobile/app/new/features/track/components/SparklineChart.tsx
- packages/core-mobile/app/new/features/track/components/TokenDetailChart.tsx
- packages/core-mobile/app/new/features/track/components/TokenHeader.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/_layout.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/trackTokenDetail/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/track/index.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/track/tokenDetail.tsx
- packages/core-mobile/app/new/routes/(signedIn)/_layout.tsx
- packages/core-mobile/app/screens/watchlist/useTokenDetails.ts
- packages/core-mobile/app/store/viewOnce/slice.ts
- packages/core-mobile/patches/react-native-graph+1.1.0.patch
- packages/k2-alpine/src/components/Header/BalanceHeader.tsx
- packages/k2-alpine/src/components/PriceChangeIndicator/PriceChangeIndicator.tsx
- packages/k2-alpine/src/components/SegmentedControl/SegmentedControl.tsx
- yarn.lock
**Ticket: [CP-9925]** 
https://github.com/user-attachments/assets/684efcfe-441e-4eed-b389-a7441ef2695b
| light | dark |
| --- | --- |
| <img src=https://github.com/user-attachments/assets/5b50985d-8079-4eeb-b163-a6cdf4e40df5 width=320 /> | <img src=https://github.com/user-attachments/assets/1ee7b4f2-f204-4397-8864-160fb83061ff width=320 /> |\
[CP-9925]: https://ava-labs.atlassian.net/browse/CP-9925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9925: Interactive Chart in Track Token Detail

- packages/core-mobile/app/screens/rpc/components/v2/ApprovalPopup.tsx
- packages/core-mobile/app/services/gasless/GaslessService.ts
**Ticket: [CP-9983]** 
This removes gasless switch from all other tx types other than ETH_SEND_TRANSACTION
[CP-9983]: https://ava-labs.atlassian.net/browse/CP-9983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-9983: Refactor gasless service to improve eligibility checks.

- packages/core-mobile/app/screens/browser/Browser.tsx
**Ticket: [CP-9984]** 
* Set url and add history when finished loading in onLoad callback, to prevent address bar spoofing 
https://github.com/user-attachments/assets/4fb026ec-75dd-4c31-bba3-ff8f0e580d17
https://github.com/user-attachments/assets/25b7d592-78c9-43de-952f-b9ffae148f3a
* Please refer to the [link](https://ava-labs.atlassian.net/jira/software/c/projects/CP/boards/60?selectedIssue=CP-9984) for the reported bug details.
* Visit the mock attacker’s website (https://muhnabil04.github.io/halodek/spoof.html) and check if the address bar incorrectly displays google.com:81 while showing the message: `This is not Google. This is a hacker website.`, 
* You can compare it with the existing behavior on Android. iOS had no such issue.
[CP-9984]: …
> CP-9984: Set url and history when finished loading

- packages/core-mobile/app/screens/rpc/components/v2/SessionProposal/SessionProposal.tsx
- yarn.lock
- use png or ico as logo on WC approval screen
- if no matching logo found, use fallback icon
when no logo is found, use dapp name initial
> Use first png or ico as WC approval logo

- packages/core-mobile/app/components/EditFees.tsx
- packages/core-mobile/app/components/NetworkFeeSelector.tsx
- packages/core-mobile/app/components/SubTextNumber.tsx
- packages/core-mobile/app/components/TokenAddress.tsx
- packages/core-mobile/app/hooks/useGasless.ts
- packages/core-mobile/app/screens/rpc/components/v2/ApprovalPopup.tsx
- packages/core-mobile/app/screens/rpc/components/v2/NetworkFeeSelectorWithGasless.tsx
- packages/core-mobile/app/screens/send/components/SendTokenForm.tsx
- packages/core-mobile/app/utils/FormatCurrency.test.ts
- packages/core-mobile/app/utils/FormatCurrency.ts
- packages/core-mobile/app/utils/numberToSubscriptFormat/numberToSubscriptFormat.test.ts
- packages/core-mobile/app/utils/numberToSubscriptFormat/numberToSubscriptFormat.ts
- packages/core-mobile/storybook/stories/FeeSelector.stories.tsx
- yarn.lock
**Ticket: [CP-10043]** 
support subtext notation in gas widget when gas has a lot of 0s
please retest all transactions (send/swap/bridge) across networks (mainnets/testnets). when there are lots of 0s, it should display with the subtext notation.
[CP-10043]: https://ava-labs.atlassian.net/browse/CP-10043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10043: Gas widget update

- packages/core-mobile/docs/patches.md
- packages/core-mobile/patches/react-native-webview-crypto+0.0.26.patch
- packages/core-mobile/polyfills/crypto.js
- yarn.lock
For some reason, with the new react native, if the webview is not rendered, nothing will work (all the javascript injection, message relaying,...). To fix it, I patched the lib so that the webview is still rendered but won't be visible.
> Fix crypto.subtle

- packages/core-mobile/app/new/features/portfolio/defi/hooks/useDeFiProtocols.ts
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
* The sort feature on the DeFi screen was removed during the [refactoring process](https://github.com/ava-labs/core-mobile/pull/2348/). This restores it.
> Fix: sort in defi

- packages/core-mobile/__mocks__/expo-router.js
- packages/core-mobile/app/new/routes/_layout.tsx
- packages/core-mobile/app/new/routes/sessionExpired.tsx
- packages/core-mobile/app/seedless/store/listeners.ts
**Ticket: [CP-10130]** 
- add sessionExpired screen to ask user to re-authenticate 
- show native alert when user uses wrong social account
- 
https://github.com/user-attachments/assets/51cf9e02-e9c5-4d1c-b885-8aad2f08546c
updated modal presentation
https://github.com/user-attachments/assets/69cd16ae-85df-4a86-8301-b85b7290ad86
[CP-10130]: https://ava-labs.atlassian.net/browse/CP-10130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10130: seedless session expired handler

- packages/core-mobile/app/services/earn/EarnService.ts
- packages/core-mobile/app/services/earn/types.ts
- packages/core-mobile/app/services/earn/utils.ts
- packages/core-mobile/app/store/notifications/listeners/scheduleNotificationsForActiveStakesPeriodically.ts
- packages/core-mobile/app/utils/network/glacier.ts
* Fetch staking transactions using backend filters(`AddDelegatorTx`, `AddPermissionlessDelegatorTx`)
* When fetching stakes for scheduling completion notifications, only include stakes from within the past year, since earlier ones can't be active
> Stake fetching improvements.

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenDetail.tsx
**Ticket: [CP-10436]** 
* Fix bug where content is not shown when using paddingTop in contentContainerStyle with CollapsibleTabs.
[CP-10436]: https://ava-labs.atlassian.net/browse/CP-10436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: no token breakdown for p/x chain on Android

- packages/core-mobile/app/new/common/components/NavigationRedirect.tsx
- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
**Ticket: [CP-10343]** 
This pr prevents users from being able to press the back button on the Pin screen to unlock the wallet. Also adds logic to show "Are you sure you want to exit?" alert when users try to quit the app. 
when users are already logged in
https://github.com/user-attachments/assets/9e79b02f-b12c-418f-886b-56acb123dd29
when users just completed onboarding
https://github.com/user-attachments/assets/6712ddd1-cdfb-4088-b7ae-91ae70949d6d
[CP-10343]: https://ava-labs.atlassian.net/browse/CP-10343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10343: Prevent tapping back on the pin screen

- packages/core-mobile/app/new/common/components/ListScreen.tsx
- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
After the fix for the margin top offset on modals for Android, the bottom padding on modals and secondary modals broke.
I think it's because of react-native's metro bundler status bar 
Made the fix for production and kept the dev mode values otherwise dev mode looks broken on android
> fix bottom padding after top offset fix

- packages/core-mobile/app/new/common/hooks/useTokenDetails.ts
- packages/core-mobile/app/new/features/track/components/ShareChart.tsx
- packages/core-mobile/app/new/features/track/screens/TrackShareScreen.tsx
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/track/index.tsx
**Ticket: [CP-10536]** 
- fix incorrect share route
- pass searchText into TrackTokenDetail and TrackShareShare, to fetch the token from react query cache, then get the token by token id
https://github.com/user-attachments/assets/58d1a9b1-ffdb-4dee-a701-a32dcb564298
[CP-10536]: https://ava-labs.atlassian.net/browse/CP-10536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10536: Fix tokenDetail

- packages/core-mobile/app/new/features/accountSettings/utils/isValidAddress.ts
**Ticket: [CP-10495]** 
[CP-10495]: https://ava-labs.atlassian.net/browse/CP-10495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10495: only use ethers isAddress to check evm address

- packages/core-mobile/app/new/common/components/ListScreen.tsx
- packages/core-mobile/app/new/common/components/ScrollScreen.tsx
- packages/core-mobile/app/new/common/consts/screenOptions.tsx
- packages/core-mobile/app/new/common/hooks/useModalScreenOptions.tsx
- packages/core-mobile/app/new/features/portfolio/collectibles/components/CollectibleManagementScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
Fixes
- CollectibleManagementScreen didn't needed isModal prop
- scrollable screens border separator animation when scrolling
- modal top margin offset fix for all devices (was broken because header height was not consistent before)
https://github.com/user-attachments/assets/7ed04815-00d5-4a9b-a058-ab342bbde22f
Broken and fixed modal top margin
> Scrollable separator animation + modal top margin fix

- packages/core-mobile/android/app/src/debug/AndroidManifest.xml
- packages/core-mobile/android/app/src/debug/res/xml/network_security_config.xml
This allows building and running debug builds on real Android devices. iOS is already possible. When being asked for a url, just specify your computer's ip address. you can use this command `ipconfig getifaddr en0` to grab the ip address.
> allow all traffic for android debug builds

- packages/core-mobile/app/new/common/components/Logo.tsx
- packages/core-mobile/app/new/features/approval/components/BalanceChange/BalanceChange.tsx
- packages/core-mobile/app/new/features/approval/components/BalanceChange/TokenDiffGroup.tsx
* Show logos for tokens that don’t have a symbol or name.
* use expo-image to handle cases where logoUri redirects to another url
* Fix layout issue when Balance Change only has an “in” value
| before | after |
| --- | --- |
| <img src=https://github.com/user-attachments/assets/6769869e-e042-42b0-bb49-da23eab24817 width=320 /> | <img src=https://github.com/user-attachments/assets/8e82eace-009e-4161-a6eb-4f0fa4fd7b56 width=320 /> |
> Fix layout of Balance Change section on the approval screen

- packages/core-mobile/app/new/features/send/components/SendToken.tsx
- packages/core-mobile/app/new/features/stake/hooks/useAddStake.ts
- make "not enough AVAX" alert clearer
- fix send to not being able to handle long text
> adjust not enough AVAX alert and fix send UI bug

- packages/core-mobile/app/new/common/consts/screenOptions.tsx
- packages/core-mobile/app/new/common/hooks/useModalScreenOptions.tsx
dismissing a modal via gesture for some reason results in some flickering on Android. for now, looks like the best solution is just to use 0 duration transition on Android to prevent the flickering. the drawback is that it also affects the transition when pressing physical back button.
**before**
https://github.com/user-attachments/assets/bbeb7d85-e0e4-436c-8b1d-44b8f375510a
**after**
https://github.com/user-attachments/assets/ab56d2e6-07ad-42e0-bcac-b5f8cc393570
> Fix bottom sheet flickering on Android

- packages/core-mobile/app/new/common/components/BalanceText.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/ActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/PendingBridgeTransactionItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItemTitle.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenDetail.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/XpActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiCommonRow.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiLendingSection.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiPortfolioInsuranceBuyer.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiPortfolioPerpetual.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiPortfolioReward.tsx
- packages/core-mobile/app/new/features/portfolio/defi/components/DeFiPortfolioVesting.tsx
- packages/k2-alpine/package.json
- packages/k2-alpine/src/components/Animated/AnimatedText.tsx
- packages/k2-alpine/src/components/PriceChangeIndicator/PriceChangeIndicator.tsx
- yarn.lock
* https://ava-labs.atlassian.net/browse/CP-10537
* https://ava-labs.atlassian.net/browse/CP-10534
| | Privacy mode is on |
| --- | --- | 
| Defi detail | <img src=https://github.com/user-attachments/assets/0e9ff202-dcbc-4170-b011-3177c0b44362 width=320 /> | 
| Portfolio token detail | <img src=https://github.com/user-attachments/assets/c4202d80-57de-4aaa-a201-11dc6803f992 width=320 /> | 
| Portfolio token detail - p/x chain | <img src=https://github.com/user-attachments/assets/7c2b9260-ead8-400b-930a-a28d164dd9de width=320 /> |
> CP-10537: Fix price change indicator layout + mask additional balances when privacy mode is on

- packages/core-mobile/app/new/features/portfolio/assets/hooks/useAssetsFilterAndSort.ts
**Ticket: [CP-10448]**
* do not pin primary tokens in portfolio
[CP-10448]: https://ava-labs.atlassian.net/browse/CP-10448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10448: Fix portfolio sorting to no longer pin primary tokens

- packages/core-mobile/app/new/features/stake/screens/ClaimStakeRewardScreen.tsx
**Ticket: [CP-10668]** 
* do not show network fee section when balance is not sufficient 
[CP-10668]: https://ava-labs.atlassian.net/browse/CP-10668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10668: do not show network fee section when balance is not sufficient

- packages/core-mobile/app/new/features/track/components/TokenHeader.tsx
**Ticket: [CP-10465]** 
* Fix to show logo placeholder when logo is not available in token detail screen
[CP-10465]: https://ava-labs.atlassian.net/browse/CP-10465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10465: Fix to show logo placeholder when logo is not available

- packages/core-mobile/app/store/network/slice.ts
we were re-rendering a lot unnecessarily because selectEnabledNetworks wasn't being memoized
> fix selector not being memoized 

- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/account.tsx
- packages/core-mobile/app/store/balance/slice.ts
- packages/core-mobile/app/store/index.ts
- packages/core-mobile/app/store/migrations.ts
**Ticket: [CP-10681]** 
- add migration to default activeNetwork to avalanche c-chain
- update selectTokensWithZeroBalance to selectTokensWithZeroBalanceByNetwork, since we only need to get the zero balance tokens for avalanche c-chain network on swap screen
- fetch account balance when account detail screen is focused
https://github.com/user-attachments/assets/aed39459-45cd-4311-8b41-faa8b9df3bcc
[CP-10681]: https://ava-labs.atlassian.net/browse/CP-10681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10681: fetch balance on account detail 

- packages/core-mobile/app/new/common/hooks/useIsSwapListLoaded.ts
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
- packages/core-mobile/app/new/features/track/trending/components/TrendingScreen.tsx
this is to make sure we render the buy/swap button correctly. currently if users go to track screens too quickly and the swap list is not loaded, we will render view button since we have no data yet.
> make track screens wait for swap list to load before rendering

- packages/core-mobile/android/app/src/main/res/values-night/colors.xml
- packages/core-mobile/android/app/src/main/res/values/colors.xml
- packages/core-mobile/android/app/src/main/res/values/styles.xml
**Ticket: [CP-10621]** 
We were using the same color for both dark and light themes. This pr adds `values-night` folder which contains colors to be used in dark mode.
[CP-10621]: https://ava-labs.atlassian.net/browse/CP-10621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10621: Fix Android Alert Button Color

- packages/core-mobile/app/new/features/accountSettings/screens/manageNetworks/ManageNetworksScreen.tsx
**Ticket: [CP-10750]** 
Refactored networks screen to mimic a sectionlist with 3 sections.
- each section result is sorted by enabled and then disabled networks
- searching will keep the sections visible and will be hidden if there is no result from that category of networks
https://github.com/user-attachments/assets/44398745-bf8b-4211-a045-4a8d5f0bd7c5
[CP-10750]: https://ava-labs.atlassian.net/browse/CP-10750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show Networks in Tabbed/Stacked View

- packages/core-mobile/app/new/features/onboarding/components/SetWalletName.tsx
**Ticket: [CP-10763]** 
Disable sticky footer on setWalletName
[CP-10763]: https://ava-labs.atlassian.net/browse/CP-10763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10763 Unable to move forward from name your wallet screen

- packages/core-mobile/app/services/notifications/NotificationsService.ts
**Ticket: [CP-10878]** 
we adjusted the subtitle from "Stake Complete" to "Stake complete alerts" so that we could display it in Notification Preferences screen. however we were still using subtitle in the notification, which causes the bug. this pr adjusts it to use the channel name instead.
[CP-10878]: https://ava-labs.atlassian.net/browse/CP-10878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10878: use channel name instead of subtitle for notification body

- packages/core-mobile/app/contexts/DeeplinkContext/utils/handleDeeplink.ts
- packages/core-mobile/app/new/common/screens/SelectNetworkScreen.tsx
- packages/core-mobile/app/new/features/bridge/screens/SelectBridgeTokenScreen.tsx
- packages/core-mobile/app/new/features/receive/screens/SelectReceiveNetworkScreen.tsx
- packages/core-mobile/app/new/features/send/screens/SelectSendTokenScreen.tsx
- packages/core-mobile/app/new/features/swap/screens/SelectSwapTokenScreen.tsx
- packages/core-mobile/app/new/features/track/utils/utils.ts
**Ticket: [CP-10881]** 
there are actually 2 issues that cause the infinite loading screen
1/ the track token details screen requires both a coingecko id and market type SEARCH to function correctly. we were passing only coingecko id from the deeplink
2/ we weren't handling undefined token in `getTokenAddress`, which makes `useTokenDetails` hook throw an error when it tries to calll `setTokenInfo`
this pr also fixes these issues:
- select token screen (in swap/send/bridge) doesn't handle long token name correctly
- select network screen in bridge shows "also supporting" evm networks
https://github.com/user-attachments/assets/5f296108-35b2-4b43-940c-c1ade2751e8a
please retest price alert push notification as well as checking all the select token/network screens
Please check all that apply …
> CP-10881: Fix unable to view token detail via price alert push notification 

- packages/core-mobile/app/new/common/hooks/useSearchableTokenList.ts
**Ticket: [CP-10897]** 
the merging of Glacier tokens with https://proxy-api.avax.network/tokens?evmChainId=43114 wasn't working because the addresses have different casing. this PR fixes it by converting all addresses to lowercase.
```
tokensWithBalanceIDs {
"avalancheavax": true,
"0x0c7d9adcd4bab7783a477c76f9492da0e1ce00ca": true,
"0x152b9d0fdc40c096757f570a51e494bd4b943e50": true,
"0x49d5c2bdffac6ce2bfdb6640f4f80f226bc10bab": true,
"0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7": true,
"0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e": true,
"avax-p": true,
"bitcoinbtc": true,
"etheth": true,
...
}
```
[CP-10897]: https://ava-labs.atlassian.net/browse/CP-10897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> CP-10897: Deduplicate tokens in select a token screen 

- packages/core-mobile/app/new/features/send/components/SendToken.tsx
**Ticket: [CP-10911]** 
https://github.com/user-attachments/assets/5cc4cdbd-3645-4f0f-9af4-8950ee810993
[CP-10911]: https://ava-labs.atlassian.net/browse/CP-10911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10911: show manually entered address by default in send flow

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
**Ticket: [CP-10404]** 
Moved the toast triggering before switching isDeveloperMode redux state
[CP-10404]: https://ava-labs.atlassian.net/browse/CP-10404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10404 [Testnet] too slow to switch testnet and mainnet

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/addStake/confirm.tsx
- packages/core-mobile/app/services/earn/EarnService.ts
- packages/core-mobile/app/services/notifications/NotificationService.test.ts
- packages/core-mobile/app/services/notifications/NotificationsService.ts
- packages/core-mobile/app/store/notifications/listeners/handleProcessNotificationData.ts
- packages/core-mobile/app/store/notifications/types.ts
**Ticket: [CP-11104](https://ava-labs.atlassian.net/browse/CP-11104)** 
This PR updates the stake complete notification system to use account IDs instead of account indices, making the account selection process more reliable and deterministic.
- Modified `EarnService` to use account IDs instead of indices when tracking stake transactions
- Updated `NotificationsService` to handle account IDs in notification data
- Enhanced notification data processing to prioritize account ID over legacy account address
- Updated type definitions to reflect the account ID-based approach
In …
> CP-11104: Migrate stake complete notification to use accountId 

- packages/core-mobile/app/seedless/services/transformKeyInfosToPubkeys.ts
**Ticket: [CP-10837]** 
On my seedless account there was null key sets on indexes 2 and 3 but existing key set on index 4. This made `transformKeyInfosToPubKeys` fail and thus never initialized Seedless wallet after onboarding.
This fixes it
https://github.com/user-attachments/assets/e95e97e9-c703-4f58-9d76-3a2b8588ce89
[CP-10837]: https://ava-labs.atlassian.net/browse/CP-10837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10837 Fail to fetch the full balance after the first login

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
- packages/core-mobile/app/seedless/store/listeners.ts
- packages/core-mobile/app/store/account/listeners.ts
**Ticket: [CP-10837]** 
* Fixed it to call `refreshPublicKeys` in the `initAccounts` listener to ensure the Seedless wallet has public keys before creating accounts. We don’t need to call `refreshPublicKeys` every time the active Seedless wallet changes, since we support only one Seedless wallet and its keys should already be available from storage.
[CP-10837]: https://ava-labs.atlassian.net/browse/CP-10837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10837: Call refreshPublicKeys in the initAccounts listener

- packages/core-mobile/app/new/common/hooks/useDeriveAddresses.test.ts
- packages/core-mobile/app/new/common/hooks/useDeriveAddresses.ts
- packages/core-mobile/app/new/common/hooks/usePrivateKeyImportHandler.ts
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/importPrivateKey.tsx
**Ticket: [CP-10839]** 
- added spinner while importing
- display total Balance and derived addresses only when private key is valid
- disable button while private key is invalid
- disable button when isImporting is true
[CP-10839]: https://ava-labs.atlassian.net/browse/CP-10839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10839 - [Import key feature] Should not add "no accounts in this wallet" section if it's empty

- packages/core-mobile/app/errors/swapError.ts
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
**Ticket: [CP-11060]** 
- Display slippage field in case there is error
- small fix for manageAccounts searching 
[CP-11060]: https://ava-labs.atlassian.net/browse/CP-11060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11060 - Swap - Can't update slippage tolereance 

- packages/core-mobile/app/new/features/accountSettings/components/AccountButtons.tsx
- packages/core-mobile/app/seedless/services/storage/SeedlessPubKeysStorage.ts
- packages/core-mobile/app/store/account/thunks.ts
…in account thunk
**Ticket: [CP-11189](https://ava-labs.atlassian.net/browse/CP-11189)** 
- Hid the `remove account` button on the account buttons if wallet type is `SEEDLESS`
- Added extra safe guard to `removeAccountWithActiveCheck` to prevent the deletion of `SEEDLESS` wallets 
| Wallet Type | Delete Account Behavior |
|-------------|------------------------|
| Mnemonic Wallet | <video src="https://user-images.githubusercontent.com/14a8bf4a-3fbb-4d30-a895-629e99efaa71" controls></video> |
| Seedless Wallet | <video src="https://user-images.githubusercontent.com/339637d7-3ce9-46a3-b017-31da35f950d8" controls></video> |
- Manually created a few accounts on a seedless wallet, viewed account details, proved you can no longer delete 
- Manually created a few accounts on a mnemonic wallet, …
> CP-11189: Implement Remove Seedless wallet public keys 

- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/screens/TokenDetailScreen.tsx
- packages/core-mobile/app/new/features/portfolio/screens/PortfolioScreen.tsx
- packages/core-mobile/app/types/analytics.ts
**Ticket: [CP-11118]** 
**New Analytics Events Added**:
- Added `PortfolioManageTokenListClicked` to track clicks on the token management list.
- Added `PortfolioAssetsClicked`, `PortfolioCollectiblesClicked`, and `PortfolioDeFiClicked` for segment selection tracking in the portfolio screen.
- Updated `PortfolioTokenSelected` parameters (`name`, `symbol` and `chainId`) for tracking token selection.
- Updated `ExplorerLinkClicked` to replace `ActivityCardLinkClicked` for tracking explorer link interactions.
**Unused Analytics Events Removed**:
- Removed events `PortfolioPrimaryNetworkClicked`, `PortfolioSecondaryNetworkClicked`, `TokenListTokenSelected`, `TokenReceiveClicked`, `TokenSendClicked`, `TokenSwapClicked`, `TokenBridgeClicked`, `CollectibleItemClicked`, `CollectibleSendClicked`, …
> CP-11118: Portfolio Event Tracking

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/securityAndPrivacy.tsx
- packages/core-mobile/app/store/app/listeners.ts
- packages/core-mobile/app/store/settings/securityPrivacy/slice.ts
- packages/core-mobile/app/store/settings/securityPrivacy/types.ts
**Ticket: [CP-10882]** 
- Added new field with toggle in security & privacy
- Added in redux lockWalletWithPIN
- Added alert before disabling
- Added check in app listener to skip verification if lockWalletWithPIN is false
https://github.com/user-attachments/assets/18e9a90c-bfde-460f-8bf5-d35c4f539fd9
[CP-10882]: https://ava-labs.atlassian.net/browse/CP-10882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10882 - Remove PIN/Bio requirement when app is open and backgrounded

- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
**Ticket: [CP-10892]** 
Check if Use touch Id is disabled and trigger a focus for PIN input
https://github.com/user-attachments/assets/de04acf7-2eae-47e0-af15-07c01cdde8e1
[CP-10892]: https://ava-labs.atlassian.net/browse/CP-10892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-10892 - If touch id is disabled then the pin pad is not auto populated on lock screen

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/verifyPinForPrivateKey.tsx
**Ticket: [CP-11305]** 
* Wallets like Metamask sometimes provide private keys that don’t start with 0x. This fixes an issue where such private keys wouldn’t be displayed properly after being imported.
[CP-11305]: https://ava-labs.atlassian.net/browse/CP-11305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11305: Fix to display the private key without a leading 0x

- packages/core-mobile/app/services/wallet/WalletFactory.ts
- packages/core-mobile/app/store/account/listeners.ts
**Ticket: [CP-11342]** 
* Fix to refresh when no public key is stored during Seedless wallet creation.
[CP-11342]: https://ava-labs.atlassian.net/browse/CP-11342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11342: Refresh when no public key is stored during Seedless wallet creation. 

- packages/core-mobile/app/new/common/components/WalletCard.tsx
- packages/core-mobile/app/new/features/accountSettings/components/AccountButtons.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/manageAccounts.tsx
- packages/core-mobile/app/store/account/slice.ts
- packages/core-mobile/app/store/account/thunks.ts
- packages/core-mobile/app/store/wallet/thunks.ts
**Ticket: [CP-11357]** 
This PR implements a visual grouping feature for private key accounts in the Manage Accounts screen. All imported private key accounts are now displayed under a single collapsible "Imported" section while maintaining the underlying wallet structure.
1. Virtual Wallet Display (manageAccounts.tsx)
Groups all private key accounts under "Imported" section
Maintains separate display logic for regular wallets
2. Enhanced Account Removal (AccountButtons.tsx & thunks.ts)
Private key accounts can always be removed
Removing a private key account also removes its parent wallet
Proper active account switching when removing currently active private key account
3. Conditional Wallet Actions (WalletCard.tsx)
Added showMoreButton prop to hide dropdown for virtual wallet
4. …
> CP-11357 Show private keys as collection of single wallet in Manage accounts screen

- packages/core-mobile/app/new/features/meld/components/SelectAmount.tsx
- packages/core-mobile/app/new/features/meld/components/SelectMeldCurrency.tsx
- packages/core-mobile/app/new/features/meld/hooks/useSelectAmount.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/AssetsScreen.tsx
- packages/k2-alpine/src/components/FiatAmountInputWidget/FiatAmountInputWidget.tsx
- we decided not to show predefined amount selection for offramp
- use local currency icon 
- fix crash when currentPrice is 0 in meld select amount screen
> hide amount selection

- packages/core-mobile/app/new/features/meld/components/SelectLocale.tsx
- packages/core-mobile/app/new/features/meld/hooks/useSearchServiceProviders.ts
- packages/core-mobile/app/new/features/meld/offramp/screens/SelectLocaleScreen.tsx
- packages/core-mobile/app/new/features/meld/onramp/screens/SelectLocaleScreen.tsx
**Ticket: [CP-11547]** 
**Ticket: [CP-11546]** 
- do not reset country when exit onramp/offramp flow
- fix incorrect useSearchServiceProvider query param
- disable button if country or currency is not selected
- use local currency icon on SelectLocaleScreen
https://github.com/user-attachments/assets/b3779b7c-0422-4d84-b59c-72e014e85501
[CP-11547]: https://ava-labs.atlassian.net/browse/CP-11547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-11546]: https://ava-labs.atlassian.net/browse/CP-11546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11547: fix selectLocaleScreen bugs

- packages/core-mobile/app/new/routes/loginWithPinOrBiometry.tsx
- packages/core-mobile/app/utils/BiometricsSDK.ts
**Ticket: [CP-11518](https://ava-labs.atlassian.net/browse/CP-11518)** 
Users with "Require PIN immediately" enabled weren't being prompted for PIN when biometrics were disabled or unavailable on their device. The app would load briefly then proceed without authentication.
`SECURE_ACCESS_SET` was incorrectly set to `'BIO'` during onboarding or app updates even when biometrics weren't available, creating an inconsistent state where the app thought biometrics were enabled but they weren't available on the device.
Two-part fix to prevent and correct the inconsistent state:
- Modified `BiometricsSDK.storeEncryptionKeyWithBiometry()` to only set `SECURE_ACCESS_SET` to `'BIO'` if biometric storage succeeds
- This prevents the inconsistent state from occurring during onboarding or app updates
- …
> CP-11518: Fixes for skipping pin screen when biometrics is disabled

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/notificationPreferences.tsx
- packages/core-mobile/app/services/notifications/channels.ts
- packages/core-mobile/app/store/index.ts
- packages/core-mobile/app/store/migrations.ts
- packages/core-mobile/app/store/notifications/listeners/listeners.ts
- packages/core-mobile/app/store/notifications/listeners/setPriceAlertNotifications.ts
**Ticket: [CP-11715]** 
Adds new notification toggle for price alert movements for favorite tokens.
Includes migration to set it to ON by default
- please refer to ticket
[CP-11715]: https://ava-labs.atlassian.net/browse/CP-11715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11715 Add notification toggle for Favorite Token Price Alerts

- bitrise.yml
CI was failing because new cert has a different format and we need to upgrade this step to support it
> bump xcode-archive step to 5.8.0

- packages/core-mobile/app/store/notifications/listeners/handlePromptNotifications.ts
**Ticket: [CP-11722]** 
Fix missing notification prompt at onboarding by skipping `waitIfSolanaLaunchScreenIsYetNotDismissed` if solana feature flag is off
[CP-11722]: https://ava-labs.atlassian.net/browse/CP-11722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Notification - should alert the notification permission

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItemTitle.tsx
- packages/core-mobile/app/new/features/portfolio/assets/hooks/useTokenDetailFilterAndSort.ts
**Ticket: [CP-11740]** 
Fixes for UNKNOWN txType
- Send/Receive labels
- Swap/Send/Receive icons
- filter by Send/Receive/Swap when txType is UNKNOWN
Receive
Sent
[CP-11740]: https://ava-labs.atlassian.net/browse/CP-11740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11740 - GA - display send/receive ERC20 properly on C-Chain  

- packages/core-mobile/app/store/network/slice.ts
**Ticket: [CP-11689]** 
* Use `selectNetworks` selector instead of `getNetworksFromCache` to get networks in `selectEnabledNetworks`
[CP-11689]: https://ava-labs.atlassian.net/browse/CP-11689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11689: Fix endless spinner when upgrading app 

- packages/k2-alpine/src/components/TokenUnitInput/TokenUnitInput.tsx
**Ticket: [CP-11746](https://ava-labs.atlassian.net/browse/CP-11746)** 
Fixed regression introduced when solving for replacing "," with "." when entering asset amounts on android 
- changed `TokenUnitInput` to use `numeric` instead of `decimal` 
BEFORE
https://github.com/user-attachments/assets/813b5520-4710-42d1-adaa-0608033bd7f2
AFTER 
https://github.com/user-attachments/assets/fed0863c-0c1c-4356-b5b6-60cc948eab38
IOS 
https://github.com/user-attachments/assets/73198d94-84de-4831-b716-a818ba3697e8
- manually tested on android device 
Please check all that apply (if …
> use numeric on android text input for send flow

- packages/core-mobile/app/new/ContextApp.tsx
- packages/core-mobile/app/new/common/components/FullScreenWarning.tsx
- packages/core-mobile/app/new/common/components/JailbreakCheck.tsx
- packages/core-mobile/app/new/common/components/TopLevelErrorFallback.tsx
- packages/core-mobile/app/new/common/hooks/useUserUniqueID.ts
- packages/core-mobile/app/new/features/accountSettings/components/About.tsx
- packages/core-mobile/app/new/features/accountSettings/components/Support.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/index.tsx
- packages/core-mobile/app/resources/Constants.ts
- packages/core-mobile/app/services/sentry/SentryService.ts
- packages/core-mobile/app/services/user/UserService.ts
**Ticket: [CP-11712]** 
* Add unique user ID to help us troubleshoot more efficiently
* iOS
https://github.com/user-attachments/assets/a0191d15-781a-4406-ac20-ed0b8b4e1b73
* Android
https://github.com/user-attachments/assets/6a0d680a-c8e6-42da-bfaf-de5944504a6e
* If you’d like to check the unique user ID in the `FullScreenWarning` component, you should trigger an error that falls back to the Sentry error boundary. The easiest way is to throw an error from within a React component during render. For example:
```
const Component = (): JSX.Element => {
throw new Error("Test");
};
```
* To fall back to `TopLevelErrorFallback` in the local build, follow the steps below.
index.js
```
if (__DEV__) {
// ...
DevDebuggingConfig.LOGBOX_DISABLED && LogBox.ignoreAllLogs(true)
// Add these three lines …
```
> CP-11712: Add unique user id for troubleshooting

- packages/core-mobile/app/services/fcm/FCMService.ts
**Ticket: [CP-11169]** 
* Fix to stop showing `balance-transferred` type notifications when the app is in the foreground
[CP-11169]: https://ava-labs.atlassian.net/browse/CP-11169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11169: don't show balance-transferred notifications while foregrounded

- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/recoveryPhraseVerifyPin.tsx
- packages/core-mobile/app/new/routes/(signedIn)/(modals)/accountSettings/verifyPinForPrivateKey.tsx
**Ticket: [CP-11879]** 
- on pin verified, replace was getting called twice, wrap it with useCallback to fix it.
[CP-11879]: https://ava-labs.atlassian.net/browse/CP-11879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11879: fix double navigate issue

- packages/core-mobile/app/new/features/approval/screens/ApprovalScreen/ApprovalScreen.tsx
- packages/core-mobile/app/new/features/bridge/screens/BridgeScreen.tsx
- packages/core-mobile/app/new/features/collectibleSend/screens/RecentContactsScreen.tsx
- packages/core-mobile/app/new/features/collectibleSend/screens/ScanQrCodeScreen.tsx
- packages/core-mobile/app/new/features/send/screens/SendScreen.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapScreen.tsx
**Ticket: [CP-11810]** 
- fixes spend limit bug
- fixed navigation getState which wasn't valid by index anymore so I had to do the check by using .some
- fixed all flows send/nft send/swap/bridge with onboarding to properly navigate from tokenDetails and 
https://github.com/user-attachments/assets/9ed92e60-b534-4cad-a9b5-960ac2d7087f
[CP-11810]: https://ava-labs.atlassian.net/browse/CP-11810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11810 - spend limit + swap/send/nft/bridge with onboarding back interaction

- packages/core-mobile/app/new/common/hooks/useTokenDetails.ts
- packages/core-mobile/app/new/features/track/components/SparklineChart.tsx
- packages/core-mobile/app/new/features/track/components/TokenDetailChart.tsx
- packages/core-mobile/app/new/features/track/screens/TrackTokenDetailScreen.tsx
**Ticket: [CP-11894]** 
- set chartData to undefined before we load new chart data to show the loading state.
https://github.com/user-attachments/assets/f65526e9-4d88-4f77-98a0-dc2046af88fd
[CP-11894]: https://ava-labs.atlassian.net/browse/CP-11894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11894: show loading state when switching segment

- packages/core-mobile/app/new/routes/onboarding/mnemonic/createPin.tsx
- packages/core-mobile/app/new/routes/onboarding/seedless/createPin.tsx
- yarn.lock
- BiometricsSDK.enableBiometry() was triggered again when biometric prompt is cancel/deny and screen is unmounted.  setUseBiometrics to false to prevent it getting triggered again. (Android only issue)
Please include Screenshots / Videos of iOS and android
- Android:
https://github.com/user-attachments/assets/fa6fe4c4-cf46-4df4-ba98-cb6b3741a93d
- iOS:
https://github.com/user-attachments/assets/f838754a-dd6a-41c0-8d23-174855876ed7
Please include steps for testing happy path of your feature, and be sure to move this ticket into the "Dev Testing" column 
- go through onboarding
- deny biometric 
- biometric prompt should not prompt again on setWalletName screen
> Fix multiple biometric prompt after denying first biometric prompt (Android only)

- packages/core-mobile/app/new/common/components/NavigationRedirect.tsx
- packages/core-mobile/app/new/common/hooks/useDeepCompareMemo.ts
- packages/core-mobile/app/new/common/utils/hasRouteByName.test.ts
- packages/core-mobile/app/new/common/utils/hasRouteByName.ts
- packages/core-mobile/package.json
- yarn.lock
**Ticket: [CP-11925](https://ava-labs.atlassian.net/browse/CP-11925)** 
* iOS
https://github.com/user-attachments/assets/d8dbfbf5-c240-434b-b5fa-1d54407e54b0
* Android
https://github.com/user-attachments/assets/d1016f5c-f5dd-46ff-a5a2-343042d46171
* iOS(5937)
* Android([5938](https://app.bitrise.io/app/7d7ca5af7066e290/installable-artifacts/703126ff0ff488dc/public-install-page/9ebb6691c92d13c0dbfc2ba7b54ae1ba))
1. open the app and navigate to any screen other than Portfolio.
2. send the app to the background and wait for longer than 5 seconds to lock the app.
3. bring the app back to the foreground and unlock the app
4. verify that the app remains on the last screen visited
[CP-11925]: https://ava-labs.atlassian.net/browse/CP-11925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> CP-11925: Keep user on previous screen after unlock

- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItem.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenActivityListItemTitle.tsx
- packages/core-mobile/ios/Podfile.lock
- yarn.lock
**Ticket: [CP-11970](https://ava-labs.atlassian.net/browse/CP-11970)** 
When we pay the gas the tokens array returns 3 items.
We need to verify if all 3 symbols are the same (this means it's a send/receive with gas payed)
If they're not the same then it's a swap
Before
After
1. Swap USDC to Aave v3 AVAX (AWAVAX) 
2. Select gas payed by us
3. Check last global activity tx (it should display x AWAVAX swapped for X USDC) 
4. Also try to send WAVAX with gas
[CP-11970]: https://ava-labs.atlassian.net/browse/CP-11970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11970 - Global Activity is incorrect when swapping USDC to AWAVAX

- packages/core-mobile/app/new/features/approval/components/BalanceChange/TokenDiffGroup.tsx
**Ticket: [CP-11911](https://ava-labs.atlassian.net/browse/CP-11911)** 
- adjust width of the token symbol and displayValue so they don't overlap
Please include Screenshots / Videos of iOS and android
Please include steps for testing happy path of your feature, and be sure to move this ticket into the "Dev Testing" column 
- initiate a swap with a token that has long symbol (e.g. qiAvalanche) and long amount length
- the symbol name and amount should be truncated and not overlapped each other
[CP-11911]: https://ava-labs.atlassian.net/browse/CP-11911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CP-11911: update approval screen token width

- packages/core-mobile/app/new/features/activity/components/ActivityList.tsx
- packages/core-mobile/app/new/features/activity/hooks/useActivityFilterAndSearch.ts
- packages/core-mobile/app/new/features/activity/screens/ActivityScreen.tsx
- packages/core-mobile/app/new/features/portfolio/assets/components/TransactionHistory.tsx
**Ticket: [CP-12002]**
- xp transactions are rendered as unknown when quickly tap on activity tab after app is launched.  we should keep showing loading state until xp token is fetchd when selectedNetwork is X/P.
(please see updated video in the comment)
https://github.com/user-attachments/assets/09b0a0e7-7a48-4178-97c9-95bc809027cd
- launch the app and go to activity tab and select X or P Chain
- now the default network is saved 
- close the app and relaunch the app
- …
> CP-12002: Fix unknown XP tx in activity tab

- packages/core-mobile/app/new/common/screens/SelectTokenScreen.tsx
- packages/core-mobile/app/new/features/approval/screens/ApprovalScreen/ApprovalScreen.tsx
- packages/core-mobile/app/new/features/meld/components/SelectAmount.tsx
- packages/core-mobile/app/new/features/meld/components/SelectToken.tsx
- packages/core-mobile/app/new/features/swap/screens/SwapPricingDetailsScreen.tsx
**Ticket: [CP-12127](https://ava-labs.atlassian.net/browse/CP-12127)**
(Android) Added a setTimeout for first screen renders to hide the keyboard it's open
https://github.com/user-attachments/assets/9984e2d9-c636-4c2b-b213-8958a3768a7a
iOS - 6152
Android - 6153
1. Open up swap, focus the textinput and tap on token to …
> CP-12127 - Keyboard blocking the select a token screen

- packages/core-mobile/app/new/routes/(signedIn)/(tabs)/browser/index.tsx
**Ticket: [CP-12134]**
* iOS
https://github.com/user-attachments/assets/e914ba6c-ce1f-4014-b948-aeb27d847829
* Android
https://github.com/user-attachments/assets/dafded08-d948-4aac-82b0-2a8b5aac3d49
* iOS: 6158, Android: [6159](https://app.bitrise.io/app/7d7ca5af7066e290/installable-artifacts/21192d03e1375799/public-install-page/2dac90079fc7047a186452ec3773d08e)
* Open a deeplink with core://browser?deeplinkUrl=https%3A%2F%2Fcore.app
* Verify that only one browser tab is opened for the deeplink.
* Repeat with multiple deeplink taps — the number of tabs should not increase unexpectedly.
To test deeplinks on android, use this command
```
adb -s [YOUR_DEVICE_ID] shell am start \
-a android.intent.action.VIEW \
-d "core://browser?deeplinkUrl=https%3A%2F%2Fcore.app"
```
[CP-12134]: …
> CP-12134: Prevent multiple browser tabs from opening per deeplink

- packages/core-mobile/app/hooks/watchlist/useWatchlist.ts
- packages/core-mobile/app/new/common/hooks/useMarketToken.ts
- packages/core-mobile/app/new/features/portfolio/assets/components/TokenListItem.tsx
- packages/core-mobile/app/utils/caip2ChainIds.ts
- packages/core-mobile/app/utils/isNetworkContractToken.ts
**Ticket: [CP-12050]**
Some coin symbols and names (e.g., [fartcoin](https://solscan.io/token/9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump#metadata)) may intentionally include trailing spaces, which can cause mismatches with the data we manage in Contentful. To ensure consistent matching, this PR updates getMarketTokenBySymbol to trim the symbol before comparison.
| Before | After |
| --- | --- |
|  <img width="320" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-09-23 at 15 17 53" src="https://github.com/user-attachments/assets/4d813717-d5ce-4ae4-808a-977cafa46130" /> | <img width="320" alt="Simulator Screenshot - iPhone 16 Pro Max - 2025-09-23 at 15 17 09" src="https://github.com/user-attachments/assets/d5e2b202-d982-4ef3-bff0-9dd4367b0c98" /> |
iOS: 6198, Android: …
> CP-12050: Handle wrapped tokens and trailing spaces in market token lookup
